### ISSUE TITLE
panel only appearing as tab, ignoring 'show panel' setting for placement in bottom panel

### ISSUE THREAD

**Issue by dkebler** [steelbrain/linter-ui-default#446] opened 2017-10-07 16:58 UTC
After upgrade to 1.6.10,  Atom 1.21,0, linter 2.2.0  the panel only shows as a tab and ignores the `show panel` setting which should put it in a bottom panel as it has always been prior to my updates.

**Comment by Arcanemagus** [comment] 2017-10-09 16:09
Since Atom v1.17.0 the "panel" uses Atom's native Dock implementation. It sounds like you somehow dragged the `linter-ui-default` Dock item out of the bottom Dock, you should be able to just drag it back down there.

**Comment by AleshaOleg** [comment] 2017-11-03 19:14
I can confirm this issue. I didn't drag it to top. And actually, i can't move Linter tab to bottom.

**Comment by Arcanemagus** [comment] 2017-11-06 17:12
The default location is a Dock on the bottom of the window:
https://github.com/steelbrain/linter-ui-default/blob/f93b38c7c34e0bbce20ddb82db282295c3ee0685/lib/panel/dock.js#L45-L47

However it is allowed to be at any of the "center" locations:
https://github.com/steelbrain/linter-ui-default/blob/f93b38c7c34e0bbce20ddb82db282295c3ee0685/lib/panel/dock.js#L48-L50

It's likely that you accidentally dragged it up at some point?

In any case if you don't have something else in the bottom Dock it can be a bit confusing to drag it back in there since if you just drag it down to the general area it splits the `center` Dock item (the main editor section) into a top and bottom pane.... but it's still in the `center` Dock. You need to drag it onto the arrow that appears on the bottom to actually get it back in the Dock. How that all works is up to Atom and not something that can be controlled here.

**Comment by AleshaOleg** [comment] 2017-11-06 17:19
@Arcanemagus thanks! it's bizarre. @dkebler you should drag "Linter" tab precisely to an arrow in the bottom. This arrow will appear on the screen when you start drag tab.

**Comment by Joulious** [comment] 2017-11-21 08:53
Same issue here. Fixed it by dragging linter tab precisely to the arrow at the bottom.

**Comment by Arcanemagus** [comment] 2017-11-21 17:09
I'm going to close this issue since @dkebler hasn't responded and of those that _are_ responding it's an understanding issue with how Docks work and nothing to do with this package itself.

**Closed by Arcanemagus** 2017-11-21 17:09 UTC
Labels: question
