### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Metafaux** [steelbrain/linter-ui-default#496] opened 2018-03-19 18:58 UTC
[Enter steps to reproduce:]

1. Open JavaScript ES5 file with >1700 lines and scroll to bottom, with configured ESLint running

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
~\AppData\Local\atom\app-1.25.0\resources\app\node_modules\text-buffer\lib\screen-line-builder.js:329

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329:30)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:141:22)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:870:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:377:16)
    at TextEditorComponent.screenPositionForPixelPosition (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:2392:18)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -4:26.8.0 find-and-replace:show (input.hidden-input)
     -3:38.8.0 intentions:highlight (input.hidden-input)
     -3:38.5.0 core:copy (input.hidden-input)
     -3:36.7.0 editor:newline (input.hidden-input)
  5x -3:36.1.0 intentions:highlight (input.hidden-input)
     -3:35.5.0 core:paste (input.hidden-input)
 23x -3:30.4.0 intentions:highlight (input.hidden-input)
     -3:29.2.0 core:copy (input.hidden-input)
  3x -3:27.9.0 intentions:highlight (input.hidden-input)
     -3:27.3.0 core:paste (input.hidden-input)
     -3:25.8.0 core:save (input.hidden-input)
  4x -2:40 intentions:highlight (input.hidden-input)
     -2:39.4.0 editor:toggle-line-comments (input.hidden-input)
undefined -2:37.3.0 intentions:highlight (input.hidden-input)
     -2:31.2.0 editor:toggle-line-comments (input.hidden-input)
     -2:22.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.4.1 
linter-htmlhint 1.4.0 
linter-jsonlint 1.3.0 
linter-ui-default 1.7.1 
```

**Comment by acao** [comment] 2018-03-30 06:29
also having this issue, same version as above 1.7.1

**Comment by Arcanemagus** [comment] 2018-03-30 16:39
Duplicate of #490

**Closed by Arcanemagus** 2018-03-30 16:39 UTC
