### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by PeterB83** [steelbrain/linter-ui-default#451] opened 2017-10-31 14:19 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.10

### Stack Trace

Uncaught Error: Requested measurement of a line component that is not currently rendered

```
At /opt/atom/resources/app/src/text-editor-component.js:2268

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (/opt/atom/resources/app/src/text-editor-component.js:2257:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/opt/atom/resources/app/src/text-editor-component.js:2250:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/opt/atom/resources/app/src/text-editor-component.js:401:16)
    at TextEditorComponent.updateSync (/opt/atom/resources/app/src/text-editor-component.js:285:18)
    at TextEditorComponent.pixelPositionForScreenPosition (/opt/atom/resources/app/src/text-editor-component.js:207:18)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:243:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:178:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
  5x -0:40.6.0 core:move-right (input.hidden-input)
  5x -0:39.6.0 core:move-down (input.hidden-input)
     -0:36.9.0 core:move-up (input.hidden-input)
     -0:36.5.0 core:move-right (input.hidden-input)
     -0:34.8.0 editor:select-to-end-of-line (input.hidden-input)
     -0:33.9.0 core:move-left (input.hidden-input)
     -0:33.4.0 core:move-down (input.hidden-input)
     -0:32.8.0 core:backspace (input.hidden-input)
     -0:32.1.0 editor:newline (input.hidden-input)
     -0:30.9.0 intentions:highlight (input.hidden-input)
     -0:30.6.0 core:undo (input.hidden-input)
     -0:29.8.0 editor:newline (input.hidden-input)
     -0:24.8.0 editor:select-to-end-of-line (input.hidden-input)
     -0:24.3.0 editor:select-to-first-character-of-line (input.hidden-input)
  2x -0:23.4.0 core:backspace (input.hidden-input)
  6x -0:21 core:move-up (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.3 
autocomplete-python 1.10.3 
busy-signal 1.4.3 
django-templates 0.5.0 
intentions 1.1.5 
linter 2.2.0 
linter-flake8 2.2.1 
linter-pycodestyle 2.1.3 
linter-ui-default 1.6.10 
platformio-ide-terminal 2.7.0 
project-manager 3.3.5 
python-debugger 0.2.0 
```

**Comment by Arcanemagus** [comment] 2018-02-08 18:18
Duplicate of #418

**Comment by Arcanemagus** [comment] 2018-02-08 18:18
This can be tracked on the Atom repo at https://github.com/atom/atom/issues/15263.

**Closed by Arcanemagus** 2018-02-08 18:18 UTC
