### ISSUE TITLE
Closing Tabs does in dock toggles the Show Panel setting

### ISSUE THREAD

**Issue by pdxwolfy** [steelbrain/linter-ui-default#310] opened 2017-05-18 04:22 UTC
I reported an issue earlier that was closed after I discovered the fix; this is the same issue, but now I can see what's happening. It may indeed be a bug.

Atom 1.17.0, linter-ui-default 1.5.4

When the dock with the linter messages is on screen, there are tabs at the top of the dock. If you close all of the tabs, the dock hides itself. Once this happens, the linter no longer opens the dock. YOu have to into the settings and enable "Show Panel"; apparently closing the dock tabs causes linter-ui-default to toggle the Show Panel setting off.

**Comment by steelbrain** [comment] 2017-05-18 07:58
<img src="https://cloud.githubusercontent.com/assets/4278113/26192007/880789da-3bc9-11e7-9f3b-98003b9a8fce.gif" />

Unable to repro, unless you close the panel by clicking the `x` in it's dock container, it should only hide and show itself once errors are available for the file again depending on your `panelRepresents` and `hidePanelWhenEmpty` configs

**Comment by pdxwolfy** [comment] 2017-05-18 08:19
Do you see where it says Linter at the top of the Dock? Hover over that - you should get a close tab button. There may be two or more tabs - looks like you have two there. When you close the tabs, that's when the setting gets undone.

**Comment by steelbrain** [comment] 2017-05-18 08:20
Well yeah then it's intentional. You should hide it instead of just closing it :D

**Comment by pdxwolfy** [comment] 2017-05-18 08:20
I'll do a video tomorrow if you're still not seeing the behavior.

**Comment by steelbrain** [comment] 2017-05-18 08:22
I am seeing that behavior, I'm just saying that it's entirely intentional. You should never close the linter panel and only hide/collapse it. Linter wants to remember if the user closed it or not so toggles the config when you do so. I don't understand what's broken here 😅

**Comment by pdxwolfy** [comment] 2017-05-18 08:42
Oh, okay. Thanks. Those tabs are a new thing - or I never noticed them before the UI changes - so the behavior was confusing me.

**Comment by steelbrain** [comment] 2017-05-21 20:35
Closing as working as intended. Cheers

**Closed by steelbrain** 2017-05-21 20:35 UTC
Labels: unconfirmed bug
