### ISSUE TITLE
Uncaught TypeError: range.intersectsWith is not a function

### ISSUE THREAD

**Issue by codevallsma** [steelbrain/linter-ui-default#600] opened 2020-11-22 00:14 UTC
I don't know how the steps to reproduce this error, it keeps happeninig all the time, whenever i click the screen.

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 20.04.1
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 2.1.4

### Stack Trace

Uncaught TypeError: range.intersectsWith is not a function

```
At /home/codevallsma/.atom/packages/linter-ui-default/lib/helpers.js:105

TypeError: range.intersectsWith is not a function
    at /packages/linter-ui-default/lib/helpers.js:105:53
    at Map.forEach (<anonymous>)
    at filterMessagesByRangeOrPoint (/packages/linter-ui-default/lib/helpers.js:102:12)
    at Editor.updateTooltip (/packages/linter-ui-default/lib/editor/index.js:291:22)
    at /packages/linter-ui-default/lib/editor/index.js:232:18)
    at invokeFunc (/packages/linter-ui-default/node_modules/lodash/lodash.js:10359:23)
    at trailingEdge (/packages/linter-ui-default/node_modules/lodash/lodash.js:10408:18)
    at timerExpired (/packages/linter-ui-default/node_modules/lodash/lodash.js:10396:18)
```

### Commands

```
     -1:28.5.0 snippets:expand (input.hidden-input)
     -1:28.5.0 editor:indent (input.hidden-input)
     -1:28 snippets:next-tab-stop (input.hidden-input)
     -1:28 snippets:expand (input.hidden-input)
     -1:28 editor:indent (input.hidden-input)
     -1:22.7.0 editor:newline (input.hidden-input)
     -1:07.8.0 intentions:highlight (input.hidden-input)
  2x -1:07.6.0 core:undo (input.hidden-input)
  3x -1:04.8.0 core:move-left (input.hidden-input)
     -1:03.9.0 core:move-right (input.hidden-input)
     -0:27.1.0 intentions:highlight (input.hidden-input)
     -0:26.8.0 core:copy (input.hidden-input)
     -0:21.8.0 intentions:highlight (input.hidden-input)
     -0:21.4.0 core:paste (input.hidden-input)
     -0:11.2.0 intentions:highlight (input.hidden-input)
     -0:10.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 2.0.1 
ide-java 0.9.1 
intentions 1.1.5 
linter 3.1.1 
linter-gcc 0.9.0 
linter-ui-default 2.1.4 
remote-editor 0.2.10 
remote-sync 4.1.8 
teletype 0.13.4 
```

**Comment by aminya** [comment] 2020-11-22 00:16
Duplicate of #576

**Closed by aminya** 2020-11-22 00:16 UTC

**Comment by aminya** [comment] 2020-11-22 00:25
@codevallsma Please check if this is resolved in the latest version
