### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by jimmyadaro** [steelbrain/linter-ui-default#485] opened 2018-03-01 17:25 UTC
Atom says: _The error was thrown from the linter-ui-default package._

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.12.3
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.10

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:650

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:650:45)
    at Map.forEach (native)
    at TextEditorComponent.renderLineTiles (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:647:43)
    at TextEditorComponent.renderContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:590:18)
    at TextEditorComponent.renderScrollContainer (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:565:18)
    at TextEditorComponent.render (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:510:20)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:107:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:383:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:274:16)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:206:18)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:246:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:178:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -1:39.7.0 core:cancel (input.hidden-input)
     -1:39.6.0 editor:consolidate-selections (input.hidden-input)
     -1:39.6.0 core:cancel (input.hidden-input)
     -1:39.4.0 editor:consolidate-selections (input.hidden-input)
     -1:39.4.0 core:cancel (input.hidden-input)
     -1:39.2.0 editor:consolidate-selections (input.hidden-input)
     -1:39.2.0 core:cancel (input.hidden-input)
     -1:39 editor:consolidate-selections (input.hidden-input)
     -1:39 core:cancel (input.hidden-input)
     -1:38.7.0 settings-view:open (input.hidden-input)
     -1:32.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:32.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:31.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:31.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:19.9.0 core:close (ul.list-inline.tab-bar.inset-panel)
     -1:19.5.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-bracket-highlight 0.3.2 
auto-update-packages 1.0.1 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.17 
file-templates 0.2.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-htaccess 0.2.0 
less-than-slash 0.18.0 
linter 2.2.0 
linter-htmlhint 1.4.0 
linter-jscs 4.1.3 
linter-php 1.5.1 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
package-sync 1.1.0 
pigments 0.40.2 
sass-autocompile 0.13.5 
teletype 0.9.0 
uglify 1.3.1 
```

**Comment by Arcanemagus** [comment] 2018-03-02 23:30
Duplicate of https://github.com/atom/atom/issues/16179

**Closed by Arcanemagus** 2018-03-02 23:30 UTC
