### ISSUE TITLE
Unreadable Popup (Tooltip?)

### ISSUE THREAD

**Issue by grantstephens** [steelbrain/linter-ui-default#317] opened 2017-05-19 13:35 UTC
Since v1.17 the 'pop-up' (Unsure of exact name) is not readable:
![image](https://cloud.githubusercontent.com/assets/2863673/26249835/4ef2a186-3ca8-11e7-87f9-40533a126323.png)
Not sure if this is a linter-ui issue or where the popup is coming from- it may even be a theme problem- just not sure at this stage.
Versions:
Atom 1.17.0
linter-ui 1.5.4
linter 2.1.4
OS: Ubuntu 17.04
Theme (Synax and UI) Material Atom
Please tell me if this is in the wrong place- Thanks and apologies in advance.

**Comment by steelbrain** [comment] 2017-05-19 14:11
Hi @grantstephens 

This is actually a bug in a lot of themes, you could switch to One Light/Dark until we fix it (less than a day)
Also duplicate of #309

**Closed by steelbrain** 2017-05-19 14:11 UTC
