### ISSUE TITLE
Auto hide panel when atom fires up

### ISSUE THREAD

**Issue by pingshunhuangalex** [steelbrain/linter-ui-default#286] opened 2017-05-05 03:15 UTC
Since now the panel is integrated with tab title into the bottom dock in Atom 1.17.0, it becomes a bit annoying when the panel pops up on atom start, but the panel is kind of useful that I don't want to disable it.

Is it possible for you to give user an option to enable panel not showing itself when atom starts, but can be toggled later on when bottom docker is called. Thanks.

**Comment by steelbrain** [comment] 2017-05-05 03:38
Thanks for the feedback @pingshunhuangalex 

Atom v1.17 is beta so the latest release was intended for beta testers only. We have your request in the todo on https://github.com/steelbrain/linter-ui-default/pull/256

**Comment by Jedipedia** [comment] 2017-05-16 17:50
Now that 1.17 has hit stable, many more users are affected by this, so I hope you can fix it soon. Ideally, the panel would auto-hide when no warnings or errors were found in the currently opened file, just like before the update.

For anyone else who accidentally updated this package, you can enter the following into your command line to go back to the previous version:
```apm install linter-ui-default@1.2.3```

**Comment by steelbrain** [comment] 2017-05-16 17:51
Thanks @Jedipedia 

Working on it as we speak, should push an update in a matter of hours

**Comment by steelbrain** [comment] 2017-05-16 19:42
Fixed by https://github.com/steelbrain/linter-ui-default/pull/256

**Closed by steelbrain** 2017-05-16 19:42 UTC
Labels: missing feature
