### ISSUE TITLE
Uncaught TypeError: validateEventDispatches is not a function

### ISSUE THREAD

**Issue by yacut** [steelbrain/linter-ui-default#212] opened 2017-03-17 13:16 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.2.1

### Stack Trace

Uncaught TypeError: validateEventDispatches is not a function

```
At /Users/roman/.atom/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginUtils.js:97

TypeError: validateEventDispatches is not a function
    at Object.executeDispatchesInOrder (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginUtils.js:97:5)
    at executeDispatchesAndRelease (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/packages/linter-ui-default/node_modules/react-dom/lib/forEachAccumulated.js:24:9)
    at Object.processEventQueue (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginHub.js:257:7)
    at runEventQueueInBatch (/packages/linter-ui-default/node_modules/react-dom/lib/ReactEventEmitterMixin.js:17:18)
    at /packages/linter-ui-default/node_modules/react-dom/lib/ReactEventEmitterMixin.js:28:5)
    at handleTopLevelImpl (/packages/linter-ui-default/node_modules/react-dom/lib/ReactEventListener.js:72:24)
    at ReactDefaultBatchingStrategyTransaction.perform (/packages/linter-ui-default/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/packages/linter-ui-default/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/packages/linter-ui-default/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at dispatchEvent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactEventListener.js:147:20)
```

### Commands

```
     -2:41.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-one-light-ui)
     -2:33.5.0 tabs:close-other-tabs (input.hidden-input)
     -2:27.7.0 core:save (input.hidden-input)
  2x -1:08.8.0 vim-mode-plus:delete (input.hidden-input)
     -1:08.0 core:save (input.hidden-input)
     -0:59.3.0 tabs:close-other-tabs (input.hidden-input)
  2x -0:57.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-ternjs 0.18.2 
atom-typescript 10.1.15 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.60 
busy-signal 1.3.0 
compare-files 0.8.0 
cson 2.0.1 
cucumber 0.6.0 
docblockr 0.9.1 
docker 0.7.0 
docs-snippets 0.8.0 
editorconfig 2.2.2 
escape-utils 0.5.3 
file-icons 2.0.17 
from-and-to-json 1.0.0 
git-blame 0.4.12 
git-history 3.2.0 
git-plus 7.3.3 
git-split-diff-hyperclick 0.3.11 
git-time-machine 1.5.6 
haskell-grammar 0.4.0 
highlight-selected 0.12.0 
hyperclick 0.0.40 
intentions 1.1.2 
js-hyperclick 1.10.1 
language-babel 2.56.2 
language-cassandra-cql 0.1.2 
language-docker 1.1.7 
language-graphql 0.8.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.1.0 
linter-csslint 1.3.4 
linter-docker 0.1.4 
linter-eslint 8.1.4 
linter-flow 5.5.0 
linter-jsonlint 1.3.0 
linter-tslint 0.14.0 
linter-ui-default 1.2.1 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-codeglance 0.4.5 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
minimap-linter 1.6.0 
minimap-split-diff 0.3.6 
pdf-view 0.56.0 
pigments 0.39.1 
project-manager 3.3.3 
script 3.14.1 
set-syntax 0.3.2 
sort-lines 0.14.0 
split-diff 1.2.0 
sync-settings 0.8.1 
tester 0.3.0 
tester-jest 0.2.0 
tester-mocha 0.2.6 
vim-mode-plus 0.84.1 
```

**Comment by steelbrain** [comment] 2017-03-17 13:18
Related https://github.com/steelbrain/linter-ui-default/issues/193

**Comment by steelbrain** [comment] 2017-04-09 21:04
Anyone have any reliable steps on how to reproduce this issue reliably? I can't fix this if I can't repro it

**Comment by masza** [comment] 2017-05-30 12:24
I have the same issue:

I don't know how to reproduce it. Im new with linter and I just install it and then after restart I have this error

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.0


### Stack Trace

Uncaught TypeError: validateEventDispatches is not a function

```
At /Users/macbook/.atom/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginUtils.js:97

TypeError: validateEventDispatches is not a function
    at Object.executeDispatchesInOrder (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginUtils.js:97:5)
    at executeDispatchesAndRelease (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/packages/linter-ui-default/node_modules/react-dom/lib/forEachAccumulated.js:24:9)
    at Object.processEventQueue (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginHub.js:257:7)
    at runEventQueueInBatch (/packages/linter-ui-default/node_modules/react-dom/lib/ReactEventEmitterMixin.js:17:18)
    at /packages/linter-ui-default/node_modules/react-dom/lib/ReactEventEmitterMixin.js:28:5)
    at handleTopLevelImpl (/packages/linter-ui-default/node_modules/react-dom/lib/ReactEventListener.js:72:24)
    at ReactDefaultBatchingStrategyTransaction.perform (/packages/linter-ui-default/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/packages/linter-ui-default/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/packages/linter-ui-default/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at dispatchEvent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactEventListener.js:147:20)
```

### Commands

```
     -6:27.8.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -6:13 application:add-project-folder (atom-pane.pane.active)
     -6:10.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -4:56.9.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:59.9.0 editor:newline (input.hidden-input)
  2x -3:49.2.0 core:move-right (input.hidden-input)
     -3:48.2.0 core:save (input.hidden-input)
     -3:48.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  3x -3:27.7.0 emmet:merge-lines (input.hidden-input)
     -3:20.1.0 intentions:highlight (input.hidden-input)
     -3:18.7.0 core:backspace (input.hidden-input)
  3x -3:16 emmet:merge-lines (input.hidden-input)
  2x -3:10 bracket-matcher:select-inside-brackets (input.hidden-input)
     -2:29.8.0 intentions:highlight (input.hidden-input)
     -2:29.4.0 meteor-helper:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
busy-signal 1.4.1 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.6 
html-to-css 0.2.2 
intentions 1.1.2 
linter 2.1.4 
linter-csslint 1.3.4 
linter-eslint 8.2.1 
linter-ui-default 1.6.0 
meteor-helper 0.29.0 
minimap 4.28.2 
todo-show 1.11.0 
wakatime 7.0.3 
```

**Comment by matthewwithanm** [comment] 2017-05-30 21:37
Hey @steelbrain! I stumbled on this issue when looking into facebook/nuclide#1172. Looks like the same issue 😊. I opened PEM--/meteor-helper#62 to try to get it fixed.

**Comment by Arcanemagus** [comment] 2017-05-31 16:43
I still have no idea why React breaks itself if that changes, this isn't the first issue here related to that "functionality".

**Comment by steelbrain** [comment] 2017-06-17 01:01
Closing as external, thanks @matthewwithanm 🙇

**Closed by steelbrain** 2017-06-17 01:01 UTC
