### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by thiminhnhut** [steelbrain/linter-ui-default#497] opened 2018-03-31 02:36 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\minhnhut\AppData\Local\atom\app-1.25.0\resources\app\node_modules\text-buffer\lib\screen-line-builder.js:329

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329:30)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:141:22)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:870:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:377:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:207:18)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:246:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -1:07.9.0 application:add-project-folder (input.hidden-input)
     -0:55.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
ascii-hex 0.2.0 
atom-beautify 0.32.2 
atom-terminal 0.8.0 
atom-ternjs 0.18.3 
auto-detect-indentation 1.3.0 
auto-indent 0.5.0 
autocomplete 0.47.0 
autocomplete-clang 0.11.4 
autocomplete-swift 1.0.3 
build 0.70.0 
busy-signal 1.4.3 
colorful-json 1.1.0 
define-jump 1.0.1 
file-icons 2.1.18 
fold-functions 0.5.0 
git-diff-details 1.4.0 
git-log 0.4.1 
git-plus 7.10.2 
git-plus-toolbar 1.0.1 
goto-definition 1.3.4 
gpp-compiler 3.0.7 
highlight-selected 0.13.1 
intentions 1.1.5 
language-ini 1.19.0 
language-kotlin 0.5.0 
language-latex 1.1.1 
language-restructuredtext 1.1.0 
language-swift 0.5.0 
latex 0.49.0 
latex-autocomplete 1.1.1 
latex-tree 0.3.0 
latexer 0.3.0 
latextools 0.8.5 
line-number-color 0.2.0 
linter 2.2.0 
linter-chktex 1.3.1 
linter-gcc 0.7.1 
linter-kotlin 0.6.0 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
pdf-view 0.67.0 
platformio-ide 2.1.3 
platformio-ide-debugger 1.2.5 
platformio-ide-terminal 2.8.1 
pretty-json 2.0.0 
python-tools 0.6.9 
remember-folds 0.3.0 
resize-indent 0.3.0 
restart-atom 0.2.0 
rst-preview-pandoc 0.1.12 
script 3.17.3 
symbols-plus 0.1.1 
symbols-tree-view 0.14.0 
sync-settings 0.8.6 
table-editor 0.2.2 
tool-bar 1.1.7 
tree-view-autoresize 2.3.0 
tree-view-git-status 1.4.0 
```

**Comment by Arcanemagus** [comment] 2018-03-31 03:58
Duplicate of #490

**Closed by Arcanemagus** 2018-03-31 03:58 UTC
