### ISSUE TITLE
Uncaught TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by monzoor** [steelbrain/linter-ui-default#466] opened 2018-01-23 08:53 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.10

### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At /Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:517

TypeError: Cannot match against 'undefined' or 'null'.
    at TokenizedBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:517:38)
    at TokenizedBuffer.endRowForCodeFoldAtRow (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:701:41)
    at TokenizedBuffer.endRowForFoldAtRow (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:680:25)
    at TokenizedBuffer.isFoldableAtRow (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:392:23)
    at TextEditor.isFoldableAtBufferRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3842:39)
    at TextEditorComponent.queryLineNumbersToRender (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:927:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:378:16)
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2401:18)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at /packages/linter-ui-default/lib/editor/index.js:178:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -4:41.8.0 core:save (input.hidden-input)
     -4:34.7.0 core:copy (input.hidden-input)
     -4:28.3.0 core:paste (input.hidden-input)
     -4:27.8.0 core:save (input.hidden-input)
     -4:00.0 core:move-right (input.hidden-input)
  5x -3:59.6.0 core:backspace (input.hidden-input)
  2x -3:52.4.0 core:move-right (input.hidden-input)
     -3:51.7.0 core:backspace (input.hidden-input)
     -3:51.1.0 core:save (input.hidden-input)
     -3:34.3.0 core:cut (input.hidden-input)
     -3:28.5.0 core:undo (input.hidden-input)
     -3:26.7.0 core:save (input.hidden-input)
     -3:25.5.0 core:backspace (input.hidden-input)
     -3:25 core:save (input.hidden-input)
  3x -3:16.6.0 editor:duplicate-lines (input.hidden-input)
  2x -0:52.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-modules 1.8.0 
blade-snippets 0.2.0 
busy-signal 1.4.3 
emmet 2.4.3 
goto-definition 1.3.4 
Hydrogen 2.2.1 
intentions 1.1.5 
jslint 1.5.1 
linter 2.2.0 
linter-ui-default 1.6.10 
pigments 0.40.2 
platformio-ide-terminal 2.8.0 
react 0.17.0 
todo-show 2.1.0 
```

**Comment by Arcanemagus** [comment] 2018-03-02 23:43
Duplicate of https://github.com/atom/atom/issues/16578

**Comment by Arcanemagus** [comment] 2018-03-02 23:44
This is an Atom internal bug, please follow the above issue for any further developments, and if you can figure out a way to reliably reproduce this I'm sure they would love that!

**Closed by Arcanemagus** 2018-03-02 23:43 UTC
