### ISSUE TITLE
Failed to load the linter-ui-default package

### ISSUE THREAD

**Issue by hfenel** [steelbrain/linter-ui-default#200] opened 2017-03-16 02:41 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.1.0

### Stack Trace

Failed to load the linter-ui-default package

```
At '../node_modules/sb-react-table/styles/base.css' wasn't found in C:\Users\fenel\.atom\packages\linter-ui-default\styles\bottom-panel.less:1:0

LessError: '../node_modules/sb-react-table/styles/base.css' wasn't found
  at /packages/linter-ui-default/styles/bottom-panel.less:1:0
```

### Commands

```
     -2:39.2.0 application:open-folder (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-typescript 10.1.15 
atom-typescript-beta 11.0.1 
linter 2.1.0 
linter-ui-default 1.1.0 
qolor 0.4.1 
```

**Comment by steelbrain** [comment] 2017-03-16 02:45
Will investigate

**Comment by mkborregaard** [comment] 2017-03-19 20:03
I have this - three errors every time I open Atom: Error compiling Less stylesheet (complains the styles/base.css is not found), "Failed ot load the linter-ui-default package" with an error citing bottom.panel.less:1:0, and "Failed to activate the linter-ui-default package, (Cannot find module 'sb-event-kit'). Probably related.

**Comment by steelbrain** [comment] 2017-03-19 23:25
Hi @mkborregaard 

It's more than likely that you have a buggy theme, can you please post the name of the theme you're using and try it with the Builtin Themes?

**Comment by mkborregaard** [comment] 2017-03-20 05:23
Hi, I am actually using my own modified syntax theme, so that did sound like the likely culprit. (I use Atom Dark UI theme). But changing the syntax theme to any of the builtin themes and restarting Atom does not help. The two first errors above are thrown every time I change the syntax theme - the third only on restart of Atom.

**Comment by mkborregaard** [comment] 2017-03-20 05:26
I should say I originally started having problems with the linter-julia package (https://github.com/TeroFrondelius/linter-julia/issues/38) - the problems with linter-ui-default seem to have started when I disabled linter-julia withouth disabling linter-ui-default. I have no reenabled that package and only get errors from linter-ui-default. Don't know if that is helpful.

**Comment by mkborregaard** [comment] 2017-03-20 05:58
Uninstalling my own syntax theme completely does not solve the issue either.

**Comment by steelbrain** [comment] 2017-03-20 06:56
Here's a good ol' fix that works most of the times

```
apm uninstall linter-ui-default
apm install linter-ui-default
```
Then restart your Atom Editor

**Comment by mkborregaard** [comment] 2017-03-20 07:55
"Have you tried turning it off, then on again?" :-D
So, this worked, and I could even reinstall and use my custom syntax theme without reeliciting the error. Thanks!

**Comment by merriam** [comment] 2017-04-09 20:27
As a small FYI, I had this issue on OSX with the latest versions of everything.  That is:

1.  Choose Atom/Coniguration (cmd-,)/Updates/Update All
2.  Restart Atom
3.  See the CSS error, which triggers a couple more errors.  No longer see es-lint boxes at bottom.
4.  apm uninstall/reinstall per steelbrain
5.  Appears to work now.

So perhaps the 'fix' is to uninstall more in the update or to warn user to delete and reinstall?

**Comment by Arcanemagus** [comment] 2017-04-09 20:29
@merriam The bug is in APM not fully updating the package (or just not installing it correctly in the first place), nothing that can be done about it here.

**Comment by merriam** [comment] 2017-04-13 19:25
Well, the installer could kick an error message pointing to this bug or warn that uninstalling and reinstalling the package is necessary?

**Comment by Arcanemagus** [comment] 2017-04-13 19:33
Both the warning message saying there was something wrong, and [the bug](https://github.com/atom/apm/issues/697) itself have _nothing_ to do with this package and there is nothing that can be done about it here.

I do suspect that you are right that the problem is that `apm` isn't propagating some error message back up to the user, but I haven't been able to reproduce it reliably enough to even check that.

**Comment by grantstephens** [comment] 2017-05-07 15:44
So it seems I've also run into this issue but uninstalling and reinstalling doesn't fix it for me. Any other suggestions?

**Comment by Arcanemagus** [comment] 2017-05-07 20:27
@grantstephens I've seen some users report that it took 2-3 times of re-installing for it to work properly. Alternatively if you have Node.js installed you can remove the `node_modules` folder and run `npm install` to see the full output.

_(Note that if you try that for other packages that will break for anything that uses native modules, it's not an issue here as neither this nor a dependency of it uses those.)_

**Comment by grantstephens** [comment] 2017-05-08 08:44
Ok, so I've tried reinstalling a number of times and tried the node_modules thing. I also tried the latest version of node.js and fresh install of atom itself- still got nothing. The log file only contains the following errors:
`
[27586:0508/103843:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.

[27586:0508/103844:ERROR:nss_util.cc(842)] After loading Root Certs, loaded==false: NSS error code: -8018

[27586:0508/103846:INFO:CONSOLE(680)] "'navigate.ignore' could not set the default. Attempted default: "**/*.css"; Schema: {"title":"Ignore Pattern/Files(glob Pattern)","type":"array","default":"**/*.css"}", source: /usr/share/atom/resources/app.asar/src/config.js (680)

[27586:0508/103847:INFO:CONSOLE(975)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source: /usr/share/atom/resources/app.asar/src/text-editor-component.js (975)

[27586:0508/103848:INFO:CONSOLE(93)] "checking latest backup...", source: /home/grantstephens/.atom/packages/sync-settings/lib/sync-settings.coffee (93)

[27586:0508/103848:INFO:CONSOLE(382)] "Creating GitHubApi client with token = XXXX", source: /home/grantstephens/.atom/packages/sync-settings/lib/sync-settings.coffee (382)

[27586:0508/103848:INFO:CONSOLE(46)] "spell-check:en-za", source: /usr/share/atom/resources/app.asar/src/task.js (46)

[27586:0508/103852:INFO:CONSOLE(118)] "latest backup version XXXX", source: /home/grantstephens/.atom/packages/sync-settings/lib/sync-settings.coffee (118)
`

**Comment by Arcanemagus** [comment] 2017-05-08 15:55
If you run the following, does it work?
```ShellSession
$ cd ~/.atom/packages/linter-ui-default
$ npm install
```

**Comment by grantstephens** [comment] 2017-05-08 16:00
Yip, at first it wasn't but then I updated node.js and then it worked

**Comment by grantstephens** [comment] 2017-05-11 07:21
Ok, so I think I have isolated the problem and seems to be python related in my case- when I start atom from command line in a python2 virtualenv then all works well, but if it is a python3 virtualenv then it does not work. Not quite sure where to take this up then as it is not flake8 or pylint specific as I hard link to those.

**Comment by ptoche** [comment] 2017-05-20 01:51
Possibly related: 

    apm install linter-ui-default
    Installing linter-ui-default to /Users/.../.atom/packages 
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.4.0
    gyp info using node@6.9.5 | darwin | x64
    gyp http GET https://atom.io/download/electron/v1.3.15/iojs-v1.3.15.tar.gz
    gyp WARN install got an error, rolling back install
    gyp ERR! install error 
    gyp ERR! stack Error: connect ETIMEDOUT 52.216.82.112:443
    gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
    gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
    gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
    gyp ERR! System Darwin 14.5.0
    gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=1.3.15" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
    gyp ERR! cwd /Users/.../.atom
    gyp ERR! node -v v6.9.5
    gyp ERR! node-gyp -v v3.4.0
    gyp ERR! not ok

**Comment by Arcanemagus** [comment] 2017-05-20 02:01
@ptoche Something is very... _strange_ with your setup if it's trying to use `gyp` during installation. Are you on Atom v1.17.0?

**Comment by ptoche** [comment] 2017-05-20 02:25
@Arcanemagus. Thanks for the feedback. I'm on MacOS (Yosemite 10.10.5). I have Julia 0.5.2 and Atom 1.17.0. All updated in the last few hours/minutes. I ran ``Pkg.update()``. I have no idea what ``gyp`` is...

**Comment by Arcanemagus** [comment] 2017-05-20 02:35
`gyp` is the tool `apm` uses to build native modules, but this package has none of those so I'm unsure why it's calling out to that for you.

**Comment by ptoche** [comment] 2017-05-20 08:08
I tried again and the package was installed silently this time around. No mention of ``gyp`` anymore. Thanks @Arcanemagus for your precisions.

**Comment by steelbrain** [comment] 2017-06-17 00:59
Closing because there's a ton of different issues merged into one here, each one should be opened separately

**Closed by steelbrain** 2017-06-17 00:59 UTC
Labels: unconfirmed bug
