### ISSUE TITLE
UI doesn't update with theme change

### ISSUE THREAD

**Issue by zmb3** [steelbrain/linter-ui-default#270] opened 2017-04-23 16:15 UTC
After switching from a dark theme to a light theme the linter panel remains with a dark background, which is nearly impossible to read.

![image](https://cloud.githubusercontent.com/assets/7527103/25315129/9fc69356-280d-11e7-9aa1-8332ec1aec3b.png)

Restarting/reloading Atom doesn't help.

**Comment by steelbrain** [comment] 2017-04-23 16:17
It's gotta be a bug with the theme itself because we're using theme variable [`@base-background-color`](https://github.com/steelbrain/linter-ui-default/blob/727a6aece10d5516e5d01f5b4b4e51e4d664076e/styles/bottom-panel.less#L12). Can you please tell us the themes you're using for testing?

**Comment by zmb3** [comment] 2017-04-23 21:25
Looks like it only occurs with the Atom Material theme.  This theme is unique in that there aren't dark/light variants - it colors itself based on the syntax theme.

**Comment by Arcanemagus** [comment] 2017-04-24 17:10
This is actually a theme issue, you can see this inside the Styleguide as well (Packages -> Styleguide -> Show).

![image](https://cloud.githubusercontent.com/assets/427137/25349084/5e0a62e4-28d5-11e7-92f5-e053885bcf8a.png)
_Atom Material (UI) + Atom Material Light (Syntax)_

The problem is that the `@inset-panel-background-color` is one of the colors that _doesn't_ follow the syntax theme, as can be found [here](https://github.com/atom-material/atom-material-ui/blob/4f6fa58655ee92859a6a9ae2bbcdaf224811dc0e/styles/ui-variables.less#L43). So this is a theme issue at it's heart.

The good news? It's fixed in Atom Material (UI) v2.0!

![image](https://cloud.githubusercontent.com/assets/427137/25349203/d05e4a5e-28d5-11e7-90d5-6db85271cd46.png)
_Atom Material v2.0 (UI) + Atom Material Light (Syntax)_

It looks like this is due for release when Atom v1.17.0 hits stable.

For now you should be able to fix this in your own stylesheet, most likely just by overriding `inset-panel-background-color` but I'm not a style guy so I can't say for sure.

**Closed** 2017-04-24 17:17 UTC
Labels: confirmed bug, external, ui

**Comment by silvestreh** [comment] 2017-04-25 22:15
Fixed in Material UI 1.3.10! Sorry about that 😅
