### ISSUE TITLE
The interface displays an exception

### ISSUE THREAD

**Issue by phpluo** [steelbrain/linter-ui-default#440] opened 2017-09-18 07:48 UTC
The first time I start ATOM the time there will be black blocks as shown in the figure below, but I will not appear after a click

![2017-09-18_14-59-22](https://user-images.githubusercontent.com/15026737/30531744-d10a4b26-9c82-11e7-8933-938df3780c90.gif)
Atom: 1.20.0 x64
Electron: 1.6.9
OS: Windows 10 64
[This is my configuration and install the package](https://gist.github.com/phpluo/6b2910ec499968e787b96615fabbeca2)

**Comment by Arcanemagus** [comment] 2017-09-18 08:01
Duplicate of https://github.com/atom/atom/issues/14915

**Comment by Arcanemagus** [comment] 2017-09-18 08:02
This should be fixed in Atom v1.21.0-beta0 😉.

**Closed by Arcanemagus** 2017-09-18 08:01 UTC

**Comment by phpluo** [comment] 2017-09-18 08:21
This does not affect my programming, Just do not look good, now I has know this question,I will wait stable version realease . thank you
