### ISSUE TITLE
Transparent error box difficult to read

### ISSUE THREAD

**Issue by JGH1000** [steelbrain/linter-ui-default#315] opened 2017-05-19 05:33 UTC
I just updated to Atom 1.17 and newest linter-ui. While the new error boxes look really nice the transparency makes it very difficult to read the actual message if there is any text underneath.

Is this caused by some theme or was it intended? If the latter, any way to modify it so the background is solid?

Many thanks!

![screenshot from 2017-05-19 14-18-15](https://cloud.githubusercontent.com/assets/27884805/26234510/0b6fbe2e-3ca0-11e7-8140-92503b7306b8.png)

**Comment by Arcanemagus** [comment] 2017-05-19 05:36
Duplicate of #309. The tl;dr of which is that this looked like a theme issue, but it's common enough that this needs to be worked around.

**Closed by Arcanemagus** 2017-05-19 05:36 UTC
