### ISSUE TITLE
Tooltips are unreadably transparent with atom-theme

### ISSUE THREAD

**Issue by palimondo** [steelbrain/linter-ui-default#320] opened 2017-05-20 15:14 UTC
The error and warning tooltips are unreadably transparent with the default atom-theme.

Versions: linter-default-ui 1.5.4, atom-dark-syntax 0.28.0. 
As a point of reference, this is not a problem with one-dark-ui 1.10.

**Comment by steelbrain** [comment] 2017-05-20 15:15
Duplicate of https://github.com/steelbrain/linter-ui-default/issues/309

**Closed by steelbrain** 2017-05-20 15:15 UTC
