### ISSUE TITLE
Rendering issue with panel handle area

### ISSUE THREAD

**Issue by tsayen** [steelbrain/linter-ui-default#432] opened 2017-09-11 08:03 UTC
The package seems to be causing an issue with editor area rendering.
It causes white rectangles to appear on the bottom and left borders of the editor, in the area where the panel handles appear on mouse hover.
When the package is disabled, issue seems to disappear.
Please see demo GIF.
Will happily provide more details if needed. 

OS: Ubuntu 16.04
Atom version: 1.19.7
Package version: 1.6.8

![rendering-issue](https://user-images.githubusercontent.com/1733236/30264321-81722c14-96d8-11e7-9c43-4d5f0722e150.gif)

**Comment by steelbrain** [comment] 2017-09-11 09:44
Hi @tsayen 

Can you please report which theme you're using and the version of the theme? Also can you try with One Dark and see if that fixes this issue?

**Comment by tsayen** [comment] 2017-09-11 12:19
Hi, 
- it's Atom Dark
- yes, switching to One Dark seems to solve the issue

**Comment by Arcanemagus** [comment] 2017-09-11 15:57
Duplicate of https://github.com/atom/atom/issues/14915

**Closed by Arcanemagus** 2017-09-11 15:57 UTC

**Comment by Arcanemagus** [comment] 2017-09-11 15:58
@tsayen See that issue for more details and a workaround if this is bugging you right now, otherwise the fix has been committed to Atom and will be in a new release of Atom Soon™️.
