### ISSUE TITLE
click doesn't work anymore, linter ui loose focus of content document

### ISSUE THREAD

**Issue by EsrefDurna** [steelbrain/linter-ui-default#349] opened 2017-06-12 21:04 UTC
open a document which have eslint errors,
try clicking the error on the linter ui,
immediately all the errors disappears ,

reason linter ui loose the focus of the document which it was validating

**Comment by steelbrain** [comment] 2017-06-12 21:20
Can you tell us which version of Linter you are on?

**Comment by EsrefDurna** [comment] 2017-06-12 21:30
you mean eslint 3.16 can cause this problem ?  
testing it now, with a newer version

**Comment by EsrefDurna** [comment] 2017-06-12 21:33
I tried with eslint 3.19.0 , still reproducible

**Comment by EsrefDurna** [comment] 2017-06-12 21:34
clicking linter-ui causes linter ui that there is no document,

**Comment by EsrefDurna** [comment] 2017-06-12 21:35
its the same issue as this one
https://github.com/atom/find-and-replace/issues/903

**Comment by EsrefDurna** [comment] 2017-06-12 21:35
https://github.com/atom/find-and-replace/issues/901

**Comment by GlenCFL** [comment] 2017-06-12 21:37
Running into this issue as well. Clicking any panel whatsoever other than the central TextEditor containing the errors will result in the linter panel hiding the messages for that TextEditor. This also causes navigation to errors through the linter message panel to no longer function.

linter: 2.1.4
linter-ui-default: 1.6.1

**Comment by Xapphire13** [comment] 2017-06-13 02:09
Repros on my machine also:

linter: **1.6.1** (also happened on **1.6.0** AFAIK)

Seems you need to set `Panel Represents => Current File` in the settings

![7501a249-8b89-42e9-8e55-9205ff6e095e](https://user-images.githubusercontent.com/3392349/27062815-a4b63094-4fa2-11e7-82d7-6fc480af7fb0.gif)

**Comment by EsrefDurna** [comment] 2017-06-13 02:28
yes exactly same problem

**Comment by benoitcerrina** [comment] 2017-06-13 14:08
same here with jslint.  This started with the latest upgrade to 1.6.1

**Comment by EsrefDurna** [comment] 2017-06-13 23:45
my setting is already > set Panel Represents => Current File in the settings
and its doing it

**Comment by tomekmarchi** [comment] 2017-06-14 00:09
Same issue here

**Comment by joarwilk** [comment] 2017-06-14 13:38
+1

**Comment by GlenCFL** [comment] 2017-06-17 05:28
Linter 2.2 seems to have fixed this issue.

**Comment by tomekmarchi** [comment] 2017-06-17 16:24
@GlenCFL that's a negative on this end. The only time it stays open is when I set it to project wide not a single file.

**Comment by GlenCFL** [comment] 2017-06-17 17:02
@tomekmarchi
It might not have been 2.2 that fixed the issue. I had also reinstalled Atom, since the automatic upgrade to 1.18 had resulted in a faulty installation. I didn't check to see if this issue had been resolved until I updated Linter to 2.2.

I think there's an issue with Atom's automatic updater, at least on Windows x64.

**Comment by steelbrain** [comment] 2017-06-17 17:03
After a ton of digging around, found the Atom bug, fix will be in next stable hopefully https://github.com/atom/atom/pull/14695

**Closed by steelbrain** 2017-06-17 17:03 UTC
Labels: unconfirmed bug

**Comment by gniezen** [comment] 2017-06-20 12:23
Updating to Linter 2.2.0 on Atom 1.18.0 just fixed this for me. Woohoo! 😄

**Comment by benoitcerrina** [comment] 2017-06-20 14:03
not fixed for me

**Comment by sualko** [comment] 2017-06-20 14:52
I can confirm that it is fixed with Linter 2.2.0 and Atom 1.18.0 on Ubuntu 16.04.

**Comment by joarwilk** [comment] 2017-06-20 15:38
Not fixed for me on macOS Sierra, atom 1.18.0, linter 2.2.0
