### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by tyrollins** [steelbrain/linter-ui-default#378] opened 2017-07-02 00:19 UTC
Tried to use the atom-beautify plugin on a large file. Met with many error messages suggesting I open an issue... 

**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.2

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2132

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2132:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2128:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:373:16)
    at TextEditorComponent.updateSync (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:270:18)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:194:18)
    at HTMLElement.pixelPositionForScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-element.js:243:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:163:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -1:35 core:paste (input.hidden-input)
     -1:30.1.0 atom-beautify:beautify-editor (span.syntax--text.syntax--plain.syntax--null-grammar)
     -1:25.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-marvel-monokai.theme-one-dark-ui)
     -1:14.4.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -1:12.4.0 core:confirm (input.hidden-input)
     -1:08.4.0 atom-beautify:beautify-editor (div.line)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-material-syntax 1.0.6 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
autoprefixer 3.7.0 
busy-signal 1.4.3 
dracula-syntax 2.0.5 
duotone-dark-sea-syntax 2.1.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.7 
highlight-selected 0.13.1 
iceberg-syntax 0.2.3 
intentions 1.1.2 
language-babel 2.66.0 
language-haml 0.24.5 
linter 2.2.0 
linter-coffeelint 1.2.1 
linter-eslint 8.2.1 
linter-htmlhint 1.3.3 
linter-php 1.3.2 
linter-rubocop 2.1.1 
linter-scss-lint 3.1.0 
linter-ui-default 1.6.2 
marvel-dark-syntax 0.8.0 
marvel-monokai 0.1.0 
multi-cursor 2.1.5 
pigments 0.39.1 
Remote-FTP 1.0.0 
rspec 0.3.2 
seti-syntax 1.1.3 
seti-ui 1.8.0 
toggle-quotes 1.0.1 
translator 0.3.0 
```

**Comment by Arcanemagus** [comment] 2017-08-14 20:17
Marking as a duplicate of #414, even though it was filed long after this, as it has links to what looks to be the relevant Atom issue. Thanks for reporting this!

**Comment by Arcanemagus** [comment] 2017-08-14 20:17
Duplicate of #414

**Closed** 2017-08-14 20:17 UTC
Labels: duplicate
