### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by PRossetti** [steelbrain/linter-ui-default#416] opened 2017-08-14 18:56 UTC
I was just normally using Atom in a javascript / angularjs file, using the search function (ctrl+f) when this error started to pop up over and over again, even when I was doing nothing.

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.4

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At C:\Users\UserName\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-component.js:2168

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:2168:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:2164:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:385:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:276:18)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:202:18)
    at HTMLElement.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-element.js:243:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:168:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -1:33.6.0 editor:newline (input.hidden-input)
  4x -1:31.4.0 core:delete (input.hidden-input)
     -1:28 intentions:highlight (input.hidden-input)
     -1:27.9.0 core:copy (input.hidden-input)
     -1:27.1.0 intentions:highlight (input.hidden-input)
     -1:27 core:paste (input.hidden-input)
     -1:25.5.0 core:backspace (input.hidden-input)
  4x -1:24.5.0 core:delete (input.hidden-input)
     -1:15.2.0 intentions:highlight (input.hidden-input)
     -1:15 core:save (input.hidden-input)
     -1:11.8.0 intentions:highlight (input.hidden-input)
     -1:11.5.0 find-and-replace:show (input.hidden-input)
     -1:10.4.0 find-and-replace:focus-next (input.hidden-input)
  4x -1:06.6.0 core:confirm (input.hidden-input)
     -0:32.5.0 intentions:highlight (input.hidden-input)
     -0:32.4.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.30.4 
atom-formatter-jsbeautify 1.1.2 
atom-shell-commands 1.5.0 
atom-typescript 11.0.6 
auto-detect-indentation 1.3.0 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.10 
formatter 2.12.4 
goto-definition 1.3.4 
hyperclick 0.1.3 
intentions 1.1.5 
js-hyperclick 1.11.0 
language-jade 0.7.2 
linter 2.2.0 
linter-ui-default 1.6.4 
oceanic-next 1.0.0 
pigments 0.40.2 
```

**Comment by Arcanemagus** [comment] 2017-08-14 20:16
Duplicate of #414

**Closed by Arcanemagus** 2017-08-14 20:16 UTC
