### ISSUE TITLE
Uncaught TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by emesbi** [steelbrain/linter-ui-default#450] opened 2017-10-31 07:25 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.10

### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2387

TypeError: Cannot match against 'undefined' or 'null'.
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2387:65)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at /packages/linter-ui-default/lib/editor/index.js:178:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -3:30.8.0 pane:show-next-item (input.hidden-input)
  3x -3:23 core:save (input.hidden-input)
  4x -2:53.6.0 core:move-down (input.hidden-input)
  8x -2:52.5.0 core:move-up (input.hidden-input)
 13x -2:50.9.0 core:move-down (input.hidden-input)
 10x -2:49.2.0 core:move-up (input.hidden-input)
  2x -2:47.5.0 core:move-down (input.hidden-input)
     -2:46.7.0 core:move-up (input.hidden-input)
     -2:46.2.0 core:move-right (input.hidden-input)
  5x -2:46.1.0 core:move-down (input.hidden-input)
     -2:44.1.0 core:move-to-bottom (input.hidden-input)
     -2:43.2.0 editor:newline (input.hidden-input)
     -2:42 core:undo (input.hidden-input)
  3x -2:40.2.0 core:save (input.hidden-input)
  7x -2:29 core:backspace (input.hidden-input)
  8x -1:08.9.0 core:close (div.github-FilePatchView.is-unstaged)
```

### Non-Core Packages

```
angular2-snippets 0.4.0 
angular2-snippets-atom 0.7.0 
angularjs 0.4.0 
angularjs-snippets 0.10.18 
atom-beautify 0.30.5 
atom-bootstrap3 1.2.12 
atom-terminal 0.8.0 
atom-typescript 11.0.10 
autocomplete-ionic-framework 0.2.2 
autocomplete-ionic2-framework 0.3.2 
busy-signal 1.4.3 
emmet 2.4.3 
gpp-compiler 3.0.7 
intentions 1.1.5 
ionic-framework-snippets 1.2.1 
jslint 1.5.1 
language-vue 0.23.1 
language-vue-component 0.5.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.4.0 
linter-php 1.5.1 
linter-ui-default 1.6.10 
vue-autocomplete 0.1.1 
vue-format 0.4.0 
vue-snippets 0.6.0 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 0.14.0 
```

**Comment by Arcanemagus** [comment] 2018-03-02 23:45
Duplicate of https://github.com/atom/atom/issues/15682

**Comment by Arcanemagus** [comment] 2018-03-02 23:45
This is an Atom internal bug, please follow the above issue for any further developments, and if you can figure out a way to reliably reproduce this I'm sure they would love that!

**Closed by Arcanemagus** 2018-03-02 23:45 UTC
