### ISSUE TITLE
Uncaught TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by Ivanwangcy** [steelbrain/linter-ui-default#459] opened 2017-12-06 01:14 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.0-beta1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.10

### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2408

TypeError: Cannot match against 'undefined' or 'null'.
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2408:65)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at /packages/linter-ui-default/lib/editor/index.js:178:29)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
atom-clock 0.1.15 
atom-ide-ui 0.6.0 
atom-material-syntax 1.0.7 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.6 
atom-ternjs 0.18.3 
atom-wx 0.1.1 
autocomplete-emojis 2.5.0 
busy-signal 1.4.3 
color-picker 2.2.5 
css-snippets 1.1.0 
docblockr 0.13.2 
editorconfig 2.2.2 
emmet 2.4.3 
ex-mode 0.18.0 
file-icons 2.1.14 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-flowtype 0.17.4 
ide-typescript 0.7.0 
intentions 1.1.5 
js-hyperclick 1.12.2 
language-babel 2.80.2 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
language-vue 0.23.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-js-standard 4.1.0 
linter-scss-lint 3.1.1 
linter-ui-default 1.6.10 
MagicPython 1.0.12 
markdown-pdf 2.1.0 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-pigments 0.2.2 
monokai 0.24.0 
nuclide 0.270.0 
nuclide-format-js 0.0.41 
pdf-view 0.61.0 
pigments 0.40.2 
react-native-components 0.1.1 
react-native-snippets 0.3.0 
react-snippets 1.0.1 
set-syntax 0.4.0 
seti-syntax 1.1.3 
seti-ui 1.9.0 
sort-lines 0.18.0 
standardjs-snippets 2.6.2 
Stylus 3.1.1 
swackets 0.35.0 
sync-settings 0.8.3 
tag 0.5.0 
toggle-quotes 1.0.1 
tool-bar 1.1.0 
vim-mode-plus 1.22.0 
wxapp 0.1.0 
```

**Comment by Arcanemagus** [comment] 2018-03-02 23:32
Duplicate of #450

**Closed by Arcanemagus** 2018-03-02 23:32 UTC
