### ISSUE TITLE
Resize dock when linter panel is active

### ISSUE THREAD

**Issue by caleb531** [steelbrain/linter-ui-default#332] opened 2017-05-23 17:25 UTC
Hi @steelbrain,

Ever since the recent linter-ui-default update for Atom 1.17, I have found that the Linter dock is usually taller than there are errors in the table, which creates wasted vertical space. To solve this, I would prefer not to be resizing the dock all the time, but I would also prefer to know when there are more errors than when there is, say, only one.

Therefore, It would be great if the height of the Linter dock (when docked to the bottom, which is the most practical place for it) would auto-adjust based on the height of the inner table. Furthermore, it would be great if the user could set a max-height on the table (or max number of errors/warnings) so that the screen isn't flooded if there are a large number of errors. I don't know how feasible this is with the current Docks API, but it would be a very nice addition.

![screen shot 2017-05-23 at 10 22 40 am](https://cloud.githubusercontent.com/assets/872474/26366981/ee55590c-3fa1-11e7-9d7d-0e88b00b6cdc.png)

Thanks,
Caleb

**Comment by steelbrain** [comment] 2017-05-23 17:41
Hi @caleb531

We have a scrollbar in the Linter Panel. If you are on OSX, the default OSX settings make applications hide their scroll bars unless being used so you could try disabling that. Because we are already showing the scroll bar from css.

**Comment by caleb531** [comment] 2017-05-23 17:49
@steelbrain Yep, I was already aware of the scrollbar, but I was suggesting this feature because it would be more convenient to see more errors at a glance without needing to scroll, while still minimizing vertical space on the screen. *Is* such functionality possible with the Docks API in some manner?

**Comment by steelbrain** [comment] 2017-06-02 18:23
I think it's more of a Chromium thing that it respects OSX config and only shows scrollbars when scrolling. Furthermore it's not limited to docks, in the text editor itself the scrollbar will be hidden unless scrolling.

Also my personal opinion is that scrollbar will take constant space on the right side and wouldn't look as nice so yeah. Furthermore even if I wanted to implement this, the solution would be [a horrible](https://stackoverflow.com/questions/7492062/css-overflow-scroll-always-show-vertical-scroll-bar) one because we'd be "emulating" the bar styles when it's hidden

Closing but feel free to continue discussing

**Comment by caleb531** [comment] 2017-06-02 18:40
@steelbrain The visibility of the scrollbar is irrelevant to me. I really was just wanting to know if it's possible for an Atom dock's height to dynamically fit to its contents with the current API. It looks like you are [already overriding the dock's height](https://github.com/steelbrain/linter-ui-default/blob/74f9f139d2a85cef72e74408e3c26e6defdddee2/lib/panel/dock.js#L22), so could this be changed to set the height to the `innerHeight` of one of the child containers or something?

**Comment by steelbrain** [comment] 2017-06-02 18:45
Reading the issue again, you seem to have requested the auto-height that was present before Docks. 🤦‍♂️

**Comment by caleb531** [comment] 2017-06-02 19:40
Yep, exactly. I found that auto-height behavior to make the Linter panel blend in with my editor environment quite well, because it never took up more vertical space than it needed.

**Comment by adamreisnz** [comment] 2017-06-25 19:57
+1 for auto height and for the previous behaviour of automatically scaling (up to a maximum number of lines/height) as more or less errors were present.

> because it never took up more vertical space than it needed.

👍

**Comment by adamreisnz** [comment] 2018-01-18 08:35
@steelbrain any idea when you might be looking into this issue?

It's a persistent annoyance of the current version of the linter UI, and a major regression in my opinion from the previous implementation.

I am constantly wasting time needing to either show or hide or resize the panel. If there's many errors, I need to make the panel larger. If then afterwards there's one error, the panel feels ridiculously large and in the way, and I have to make it smaller again.

Auto resizing would be really useful to have back.

**Comment by steelbrain** [comment] 2018-01-18 17:42
Have been pretty busy with other stuff lately but I'll try to work on it if someone can ping me again this weekend :)

**Comment by adamreisnz** [comment] 2018-01-18 21:14
Would be great, I'll try to remember to ping you :) Thanks!

**Comment by adamreisnz** [comment] 2018-01-20 05:11
@steelbrain pinging you re this issue :)

**Comment by adamreisnz** [comment] 2018-02-03 18:35
@steelbrain any update on this issue?

**Comment by steelbrain** [comment] 2018-02-03 20:40
I'm sorry I forgot again 😭 Working on this right now

**Comment by adamreisnz** [comment] 2018-02-03 20:43
No worries, I know how it is 😄 
Just ran into it again today so I figured I'd check in

**Comment by steelbrain** [comment] 2018-02-04 20:10
It took me some (okay a lot SORRY!) of time but the fix is finally up in https://github.com/steelbrain/linter-ui-default/pull/475

**Comment by adamreisnz** [comment] 2018-02-04 23:21
Awesome, thank you!

**Closed** 2018-03-01 18:56 UTC
