### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by DocCaliban** [steelbrain/linter-ui-default#499] opened 2018-05-02 19:07 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 ia32
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At \Local\atom\app-1.26.1\resources\app\node_modules\text-buffer\lib\screen-line-builder.js:329

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329:30)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:141:22)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor-component.js:881:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor-component.js:385:16)
    at TextEditorComponent.screenPositionForPixelPosition (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor-component.js:2399:18)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -1:11.7.0 intentions:highlight (input.hidden-input)
     -1:11.3.0 core:copy (input.hidden-input)
     -1:11.1.0 core:move-down (input.hidden-input)
     -1:10.5.0 intentions:highlight (input.hidden-input)
     -1:10.4.0 core:paste (input.hidden-input)
     -1:05.4.0 autocomplete-plus:confirm (input.hidden-input)
     -1:03.1.0 editor:newline (input.hidden-input)
  3x -1:01.9.0 core:select-up (input.hidden-input)
  2x -1:01.0 intentions:highlight (input.hidden-input)
     -1:00.5.0 core:copy (input.hidden-input)
     -1:00.3.0 core:move-down (input.hidden-input)
     -0:59.9.0 intentions:highlight (input.hidden-input)
     -0:59.7.0 core:paste (input.hidden-input)
  4x -0:59.4.0 core:move-up (input.hidden-input)
     -0:58.6.0 core:delete (input.hidden-input)
     -0:52.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
git-blame 1.6.0 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
prettier-atom 0.53.0 
```

**Comment by Arcanemagus** [comment] 2018-05-02 19:10
Duplicate of https://github.com/atom/atom/issues/16892

**Closed by Arcanemagus** 2018-05-02 19:10 UTC
