### ISSUE TITLE
Uncaught RangeError: Invalid array length

### ISSUE THREAD

**Issue by secondnetwork** [steelbrain/linter-ui-default#423] opened 2017-08-18 07:31 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.7

### Stack Trace

Uncaught RangeError: Invalid array length

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2839

RangeError: Invalid array length
    at TextEditorComponent.populateVisibleTiles (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2839:45)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:372:16)
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2328:18)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at /packages/linter-ui-default/lib/editor/index.js:168:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -7:56.8.0 tree-view:move (span.name.icon.laravel-icon.medium-orange)
  6x -7:53.3.0 core:copy (input.hidden-input)
     -0:12.6.0 core:move-right (input.hidden-input)
  3x -0:12.4.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
autocomplete-php 0.3.7 
autocomplete-sass 0.1.0 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.11 
intentions 1.1.5 
jquery-snippets 11.0.0 
language-blade 0.34.0 
laravel 0.7.1 
linter 2.2.0 
linter-php 1.3.2 
linter-ui-default 1.6.7 
merge-conflicts 1.4.5 
minimap 4.29.6 
minimap-pigments 0.2.2 
nucleus-dark-ui 0.12.3 
php-cs-fixer 4.1.0 
php-light-syntax 1.0.2 
pigments 0.40.2 
predawn-ui 1.0.7 
seti-ui 1.9.0 
wordpress-api 1.2.2 
wp-dev 0.3.5 
```

**Comment by Arcanemagus** [comment] 2017-08-18 16:35
Duplicate of #410

**Closed by Arcanemagus** 2017-08-18 16:35 UTC
