### ISSUE TITLE
Highlights entire js file with red lines

### ISSUE THREAD

**Issue by HYUTS** [steelbrain/linter-ui-default#501] opened 2018-05-08 22:08 UTC
The only way I could prevent my entire file from being covered in red lines is to disable Linter-UI-Defualt
![screenshot 2018-05-08 15 06 30](https://user-images.githubusercontent.com/20317751/39785599-a2f59546-52d1-11e8-8c66-7dd6d2d863de.png)

**Comment by skylize** [comment] 2018-05-08 22:45
There is not enough information in your post to offer useful suggestions. Because all the code is blurred out, we cannot even tell what linter provider you are using. 

Linter UI Default simply displays messages as provided by the language-specific linter provider. So if the linting is incorrect, you need to report it to the appropriate provider. 

If you don't want to lint that file type, then you can disable the specific provider, rather than disabling the UI base package. Or for some providers, such as `linter-eslint`, you can customize the list of scopes to check, without disabling the provider altogether.

**Comment by Arcanemagus** [comment] 2018-05-10 17:54
Note that ESLint will report ranges that cover entire files if something is affecting the root node and the rule hasn't provided a better range. This is _likely_ an issue with one of the plugins in your ESLint configuration.

In any case since you haven't provided any information to reproduce this, and it's almost certainly a bug in something else (not even anything that is part of the Atom linter ecosystem...), I'm marking this as closed.

If you need help tracking this down further please file an issue on the specific provider you are using for JavaScript files.

Thanks for taking the time to file an issue!

**Closed by Arcanemagus** 2018-05-10 17:54 UTC
