### ISSUE TITLE
startup time increased from v1.5.0?

### ISSUE THREAD

**Issue by t9md** [steelbrain/linter-ui-default#318] opened 2017-05-19 16:46 UTC
I noticed startup time increased when I upgraded from v1.4.0 to v1.5.4.
I checked timecop view several time by reloading editor several time.
Here is screen capture of typical result.

- v1.4.0

<img width="957" alt="timecop_ ___github_atom-narrow" src="https://cloud.githubusercontent.com/assets/155205/26257870/2f2274d0-3cfd-11e7-9727-16c28bb87b64.png">

- v1.5.4

<img width="942" alt="timecop_ ___github_atom-narrow" src="https://cloud.githubusercontent.com/assets/155205/26257885/41a632a4-3cfd-11e7-8511-78d54d82f59d.png">

- My environment

```
$ sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.5
BuildVersion:   16F73
$
```

Is there any reason why increased startup time?
If you can fix it, it's great.

Why I'm sensitive for startup time is me too also struggling to reduce initial startup time of vim-mode-plus.

So I check time-cop view very frequently.

**Comment by Arcanemagus** [comment] 2017-05-19 16:51
Duplicate of #313.

**Closed by Arcanemagus** 2017-05-19 16:51 UTC
