### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by sgrow23** [steelbrain/linter-ui-default#490] opened 2018-03-08 13:48 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.4
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329:30)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:141:22)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:867:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:376:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:274:16)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:206:18)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:246:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -2:17.2.0 core:copy (input.hidden-input)
  4x -2:11.4.0 editor:newline (input.hidden-input)
     -2:10.7.0 core:paste (input.hidden-input)
 12x -2:03.4.0 core:move-down (input.hidden-input)
  5x -1:29.1.0 core:select-down (input.hidden-input)
     -1:25.1.0 core:delete (input.hidden-input)
  3x -1:24.1.0 core:move-up (input.hidden-input)
     -1:23.1.0 core:move-down (input.hidden-input)
  2x -1:22.7.0 core:delete (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-ruby 0.2.8 
busy-signal 1.4.3 
debug 0.0.1 
git-control 0.9.0 
git-diff-details 1.4.0 
git-log 0.4.1 
git-plus 7.10.0 
git-time-machine 1.5.9 
go-debug 1.6.0 
go-plus 5.8.2 
intentions 1.1.5 
language-yaml-cloudformation 0.3.1 
linter 2.2.0 
linter-js-cloudformation-yaml 2.2.1 
linter-ruby 1.2.6 
linter-ui-default 1.7.1 
node-debugger 1.10.1 
php-debug 0.2.6 
platformio-ide-terminal 2.8.0 
python-debugger 0.2.0 
teletype 0.9.0 
tree-view-git-status 1.4.0 
```

**Comment by michael-nischt** [comment] 2018-03-21 10:00
I'm affected by the same issue on Ubuntu 17.10. Freezes all of atom so can't even use the submit/view bug feature.. basically Atom is broken atm for me until it's fixed.

**Comment by Arcanemagus** [comment] 2018-03-30 16:41
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/16892. You may want to subscribe there for updates.

**Closed by Arcanemagus** 2018-03-30 16:41 UTC

**Comment by l3laze** [comment] 2018-04-01 06:32
For me this started occurring after I made some changes to a cross-platform project I have been developing on Mac over on Windows and then moved the files back to the Mac side. No idea if it was related to an update in the linter/etc though.
