### ISSUE TITLE
Uncaught Error: Cannot find module './editors'Require stack:- $ATOM_HOME/packages\linter-ui-def...

### ISSUE THREAD

**Issue by Monsoon-Ryan2115** [steelbrain/linter-ui-default#599] opened 2020-11-19 19:19 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 2.1.4

### Stack Trace

Uncaught Error: Cannot find module './editors'
Require stack:
- C:\Users\Monso\.atom\packages\linter-ui-default\lib\main.js
- C:\Users\Monso\.atom\packages\linter-ui-default\lib\index.js
- C:\Users\Monso\AppData\Local\atom\app-1.53.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:630

Error: Cannot find module './editors'
Require stack:
- C:\Users\Monso\.atom\packages\linter-ui-default\lib\main.js
- C:\Users\Monso\.atom\packages\linter-ui-default\lib\index.js
- C:\Users\Monso\AppData\Local\atom\app-1.53.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.53.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at LinterUI.observeShowDecorations (/packages/linter-ui-default/lib/main.js:61:19)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 2.0.1 
intentions 1.1.5 
linter 3.1.1 
linter-jshint 3.1.19 
linter-ui-default 2.1.4 
terminus 4.0.6 
```

**Comment by aminya** [comment] 2020-11-20 18:24
Unable to reproduce. How often does this happen?

**Comment by Monsoon-Ryan2115** [comment] 2020-11-20 19:01
It's happened 3 times. After that I restarted my computer, and I doesn't
happen anymore. Sorry:(

**Comment by aminya** [comment] 2020-11-20 19:05
OK. Thanks. I will close this then.

**Closed by aminya** 2020-11-20 19:05 UTC
Labels: unconfirmed bug
