### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by Bucko13** [steelbrain/linter-ui-default#224] opened 2017-03-21 06:05 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.2.1

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/decoration-manager.js:202

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/app.asar/src/decoration-manager.js:192:17)
    at TextEditor.module.exports.TextEditor.decorateMarker (/app.asar/src/text-editor.js:1727:37)
    at Editor.decorateMarker (/packages/linter-ui-default/lib/editor/index.js:246:23)
    at _loop (/packages/linter-ui-default/lib/editor/index.js:239:12)
    at Editor.apply (/packages/linter-ui-default/lib/editor/index.js:217:61)
    at /packages/linter-ui-default/lib/editors.js:52:48
    at Array.forEach (native)
    at /packages/linter-ui-default/lib/editors.js:52:23
    at Array.forEach (native)
    at Editors.update (/packages/linter-ui-default/lib/editors.js:49:15)
    at LinterUI.render (/packages/linter-ui-default/lib/main.js:67:17)
    at /packages/linter/lib/ui-registry.js:29:16
    at Set.forEach (native)
    at UIRegistry.render (/packages/linter/lib/ui-registry.js:28:20)
    at /packages/linter/lib/main.js:131:23
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at MessageRegistry.update (/packages/linter/lib/message-registry.js:130:20)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
  8x -3:31 core:backspace (input.hidden-input)
  2x -2:32.3.0 core:save (input.hidden-input)
     -1:28.6.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -1:16.6.0 editor:newline (input.hidden-input)
     -1:16.1.0 core:backspace (input.hidden-input)
  2x -1:15.6.0 editor:newline (input.hidden-input)
  2x -0:52.6.0 core:backspace (input.hidden-input)
     -0:19.4.0 core:move-right (input.hidden-input)
     -0:17.7.0 editor:newline (input.hidden-input)
     -0:14.1.0 core:save (input.hidden-input)
     -0:12.1.0 core:move-up (input.hidden-input)
     -0:11.6.0 core:move-right (input.hidden-input)
     -0:10.7.0 core:save (input.hidden-input)
     -0:05.2.0 snippets:next-tab-stop (input.hidden-input)
     -0:05.2.0 snippets:expand (input.hidden-input)
     -0:05.2.0 editor:indent (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
busy-signal 1.3.0 
hey-pane 0.2.2 
intentions 1.1.2 
language-babel 2.56.2 
linter 2.1.0 
linter-eslint 8.1.4 
linter-ui-default 1.2.1 
markdown-preview-plus 2.4.9 
material 2.2.0 
move-panes 0.2.0 
vim-mode-plus 0.84.1 
```

**Comment by steelbrain** [comment] 2017-04-10 11:55
Anyone have any reliable steps I can use to reproduce this error on my end? I can't fix it if I can't repro.

Also @Arcanemagus I haven't had this one in the longest time, have you seen it lately? My rough guess would be that this is an Atom issue

**Comment by Arcanemagus** [comment] 2017-04-10 16:08
I haven't seen this one in a while either, and can't remember if this is the same stack trace. I see `vim-mode-plus` in there, so maybe it has something to do with this?

**Comment by jmatsushita** [comment] 2017-05-10 15:30
I've seen this when installing `tester` and `tester-mocha` which also uses the gutter. yacut/tester#10

Specifically I think the steps where:
 - Install both modules and configure the gutter.
 - Run a test.
 - Try to change the configuration for gutter notifications on linter-ui-default 
 - Error message.

Cheers,

Jun

**Comment by OmgImAlexis** [comment] 2017-06-18 04:19
[Enter steps to reproduce:]

1. Randomly got this after closing a tab.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.3
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.1


### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:204

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:194:1)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1737:1)
    at /packages/linter-ui-default/lib/tooltip/index.js:33:16)
    at Editor.updateTooltip (/packages/linter-ui-default/lib/editor/index.js:219:20)
    at /packages/linter-ui-default/lib/editor/index.js:178:12
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -1:37.8.0 tree-view:remove (span.name.icon.icon-file-directory)
     -0:55.1.0 core:cut (input.hidden-input)
     -0:52.1.0 tree-view:add-file (div.tool-panel.tree-view)
     -0:47.1.0 editor:select-to-beginning-of-word (input.hidden-input)
  4x -0:46.7.0 core:select-right (input.hidden-input)
     -0:41.6.0 core:cancel (input.hidden-input)
     -0:40.5.0 core:undo (input.hidden-input)
     -0:32.2.0 tree-view:add-file (div.tool-panel.tree-view)
     -0:29.9.0 core:confirm (input.hidden-input)
     -0:28 core:paste (input.hidden-input)
  2x -0:19.9.0 core:backspace (input.hidden-input)
     -0:16.2.0 core:cut (input.hidden-input)
     -0:13.8.0 tree-view:add-file (div.tool-panel.tree-view)
     -0:11.3.0 core:confirm (input.hidden-input)
     -0:10 core:paste (input.hidden-input)
     -0:08.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autohide-tree-view 0.25.1 
busy-signal 1.4.3 
duplicate-removal 0.1.3 
editorconfig 2.2.2 
file-icons 2.1.7 
git-status 0.3.4 
intentions 1.1.2 
language-docker 1.1.8 
language-mako 0.6.0 
language-nginx 0.8.0 
language-pug 0.0.21 
language-vue 0.23.0 
linter 2.2.0 
linter-pycodestyle 2.0.2 
linter-stylelint 3.10.0 
linter-swagger 0.4.1 
linter-ui-default 1.6.1 
linter-xo 0.23.1 
multi-cursor 2.1.5 
seti-syntax 1.1.3 
seti-ui 1.8.0 
sort-lines 0.14.0 
tree-view-autoresize 2.1.0 
tree-view-git-status 1.4.0 
```

**Comment by OmgImAlexis** [comment] 2017-06-18 04:21
[Enter steps to reproduce:]

1. I have a file open that I'm splitting into new files.
2. I had 2 open files both I had just created without saving any content.
3. After closing the first I get no error.
4. After closing the second I get this error.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.3
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.1


### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:204

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:194:1)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1737:1)
    at /packages/linter-ui-default/lib/tooltip/index.js:33:16)
    at Editor.updateTooltip (/packages/linter-ui-default/lib/editor/index.js:219:20)
    at /packages/linter-ui-default/lib/editor/index.js:178:12
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -0:39.4.0 core:cut (input.hidden-input)
     -0:37.8.0 editor:select-to-first-character-of-line (input.hidden-input)
  2x -0:37.8.0 core:select-up (input.hidden-input)
     -0:37.4.0 core:backspace (input.hidden-input)
  2x -0:35 core:undo (input.hidden-input)
  2x -0:31.2.0 core:redo (input.hidden-input)
     -0:28.9.0 tree-view:add-file (div.tool-panel.tree-view)
     -0:26.8.0 core:confirm (input.hidden-input)
     -0:25.3.0 core:paste (input.hidden-input)
     -0:21.1.0 core:cut (input.hidden-input)
     -0:18.6.0 tree-view:add-file (div.tool-panel.tree-view)
     -0:16.7.0 core:confirm (input.hidden-input)
     -0:15.4.0 core:paste (input.hidden-input)
     -0:11.2.0 tree-view:move (span.name.icon.js-icon.medium-yellow)
     -0:10.7.0 core:move-right (input.hidden-input)
     -0:10 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autohide-tree-view 0.25.1 
busy-signal 1.4.3 
duplicate-removal 0.1.3 
editorconfig 2.2.2 
file-icons 2.1.7 
git-status 0.3.4 
intentions 1.1.2 
language-docker 1.1.8 
language-mako 0.6.0 
language-nginx 0.8.0 
language-pug 0.0.21 
language-vue 0.23.0 
linter 2.2.0 
linter-pycodestyle 2.0.2 
linter-stylelint 3.10.0 
linter-swagger 0.4.1 
linter-ui-default 1.6.1 
linter-xo 0.23.1 
multi-cursor 2.1.5 
seti-syntax 1.1.3 
seti-ui 1.8.0 
sort-lines 0.14.0 
tree-view-autoresize 2.1.0 
tree-view-git-status 1.4.0 
```

**Comment by OmgImAlexis** [comment] 2017-06-18 04:24
Here's a video showing the issue. https://vid.me/HavJ

Note this also happens if I save the first new tab.

**Comment by Arcanemagus** [comment] 2017-06-22 16:37
@OmgImAlexis Are you able to reproduce this on Atom v1.18.0? I unfortunately couldn't reproduce your video (which looks to be the second report) using Atom v1.19.0-beta0.

**Comment by OmgImAlexis** [comment] 2017-06-23 06:13
Looks like it's no longer an issue. This can be closed.

**Comment by Arcanemagus** [comment] 2017-06-29 20:48
Marking as closed based on the above, and that the original poster was using an ancient version of `linter-ui-default` which has been changed quite a bit.

**Closed by Arcanemagus** 2017-06-29 20:48 UTC
Labels: unconfirmed bug

**Comment by abraham** [comment] 2017-09-13 20:11
Just had this happen to me. At the time I was closing several tabs rapidly.

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.8


### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:191

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:183:27)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1811:43)
    at /packages/linter-ui-default/lib/tooltip/index.js:33:16)
    at Editor.updateTooltip (/packages/linter-ui-default/lib/editor/index.js:238:20)
    at /packages/linter-ui-default/lib/editor/index.js:194:12
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -7:23.1.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -7:22.7.0 core:backspace (input.hidden-input)
     -7:20.9.0 core:save (input.hidden-input)
     -7:04.2.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -7:04.0 core:backspace (input.hidden-input)
     -6:57.9.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -6:57.7.0 core:backspace (input.hidden-input)
  3x -6:56.8.0 core:save (input.hidden-input)
     -5:11.4.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -5:11.2.0 core:paste (input.hidden-input)
     -5:10.7.0 core:confirm (input.hidden-input)
  2x -5:07.5.0 core:backspace (input.hidden-input)
     -5:05.3.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -5:05.1.0 core:backspace (input.hidden-input)
     -5:04.8.0 core:save (input.hidden-input)
  5x -0:52.1.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-bootstrap3 1.2.12 
atom-jshint 2.0.0 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-polymer 0.13.0 
atom-ternjs 0.18.3 
atom-typescript 11.0.8 
autocomplete-ruby 0.2.8 
busy-signal 1.4.3 
file-icons 2.1.11 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.5 
language-ampscript 0.5.0 
language-crontab 1.0.0 
language-docker 1.1.8 
language-gherkin 1.0.4 
language-graphql 0.9.0 
language-haml 0.25.1 
language-slim 0.6.0 
language-typescript-grammars-only 1.6.0 
linter 2.2.0 
linter-erb 1.1.0 
linter-eslint 8.2.1 
linter-flake8 2.2.1 
linter-htmlhint 1.3.3 
linter-js-yaml 1.2.7 
linter-jscs 4.1.3 
linter-php 1.4.0 
linter-phpmd 1.5.3 
linter-polymer 0.0.3 
linter-pycodestyle 2.1.3 
linter-rubocop 2.1.1 
linter-ruby 1.2.6 
linter-tslint 1.7.0 
linter-twig 0.4.2 
linter-ui-default 1.6.8 
material-monokai-syntax 1.0.1 
merge-conflicts 1.4.5 
monokai 0.24.0 
php-twig 4.0.0 
pigments 0.40.2 
polymer-atom 0.0.8 
polymer-ide 0.4.0 
polymer-snippets 3.2.1 
prettier-atom 0.38.0 
pretty-json 1.6.4 
rails-rspec 0.3.2 
rspec 0.4.0 
ruby-solargraph 0.1.0 
sort-lines 0.15.0 
Sublime-Style-Column-Selection 1.7.4 
travis-ci-status 1.3.1 
zentabs 0.8.8 
```

**Comment by Arcanemagus** [comment] 2017-09-13 20:14
@abraham Can you file that as a new issue? There have been a few different things shoved into this issue and I'd like to keep them separated.

On that note, I'm locking this conversation to prevent further reports different from the originally reported issue from getting into this thread.
