### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by maseehussain** [steelbrain/linter-ui-default#470] opened 2018-02-01 20:06 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.10

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:646

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:646:45)
    at Map.forEach (native)
    at TextEditorComponent.renderLineTiles (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:643:43)
    at TextEditorComponent.renderContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:586:18)
    at TextEditorComponent.renderScrollContainer (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:561:18)
    at TextEditorComponent.render (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:506:20)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:107:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:383:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:274:16)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:206:18)
    at HTMLElement.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:243:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:178:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -1:35.5.0 core:move-down (input.hidden-input)
     -1:34.5.0 editor:newline (input.hidden-input)
     -1:34.2.0 core:move-up (input.hidden-input)
     -1:32.9.0 snippets:next-tab-stop (input.hidden-input)
     -1:32.9.0 snippets:expand (input.hidden-input)
     -1:32.9.0 editor:indent (input.hidden-input)
     -1:32 core:paste (input.hidden-input)
  8x -1:29.3.0 core:backspace (input.hidden-input)
     -1:26.7.0 core:save (input.hidden-input)
     -1:08.1.0 editor:newline (input.hidden-input)
     -1:06.4.0 core:paste (input.hidden-input)
  8x -1:03.9.0 core:backspace (input.hidden-input)
     -1:00.8.0 editor:newline (input.hidden-input)
     -0:58.7.0 core:backspace (input.hidden-input)
     -0:58.4.0 editor:newline (input.hidden-input)
     -0:57.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ternjs 0.18.3 
auto-indent 0.5.0 
busy-signal 1.4.3 
file-icons 2.1.12 
intentions 1.1.5 
language-babel 2.74.2 
language-ejs 0.4.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-erb 1.1.0 
linter-eslint 8.3.2 
linter-js-yaml 1.2.8 
linter-ruby 1.2.6 
linter-ui-default 1.6.10 
open-in-browser 0.5.2 
pigments 0.40.2 
ruby-block 0.3.6 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by Arcanemagus** [comment] 2018-02-02 06:02
Duplicate of #468

**Closed by Arcanemagus** 2018-02-02 06:02 UTC
