### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by midastouchprd** [steelbrain/linter-ui-default#469] opened 2018-01-30 10:19 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.10

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:646

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:646:45)
    at Map.forEach (native)
    at TextEditorComponent.renderLineTiles (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:643:43)
    at TextEditorComponent.renderContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:586:18)
    at TextEditorComponent.renderScrollContainer (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:561:18)
    at TextEditorComponent.render (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:506:20)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:107:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:383:16)
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2401:18)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at /packages/linter-ui-default/lib/editor/index.js:178:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -9:08.4.0 core:backspace (input.hidden-input)
     -9:06.6.0 core:save (input.hidden-input)
     -0:06.6.0 editor:consolidate-selections (input.hidden-input)
     -0:06.6.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-prettify 0.1.3 
atom-react-snippets 0.2.2 
busy-signal 1.4.3 
html-shorcuts-react 2.1.0 
intentions 1.1.5 
language-javascript-jsx 0.3.7 
linter 2.0.0 
linter-ui-default 1.6.10 
pigments 0.40.2 
platformio-ide-terminal 2.8.0 
prettier-atom 0.48.0 
react 0.17.0 
react-es6-snippets 0.3.0 
react-native-snippets 0.3.0 
react-redux-snippets 0.1.6 
react-snippets 1.0.1 
```

**Comment by Arcanemagus** [comment] 2018-02-02 06:02
Duplicate of #468

**Comment by Arcanemagus** [comment] 2018-02-02 06:03
Note: Marked as a duplicate because although the stack trace is slightly different, the part that actually has the issue is the same in both.

**Closed by Arcanemagus** 2018-02-02 06:02 UTC
