### ISSUE TITLE
Don't startup on 32bit, before last update.

### ISSUE THREAD

**Issue by JackPot777** [steelbrain/linter-ui-default#372] opened 2017-06-27 08:58 UTC

**Comment by steelbrain** [comment] 2017-06-27 09:12
Hi @JackPot777 

Can you provide some issue details like your Atom version and how are you trying to install this package and what exactly fails with what message?

**Comment by JackPot777** [comment] 2017-06-27 15:21
I have the atom on a 32 bit system, 1.17.0 - compiled.. This Supplement stood and worked. But after the update, stopped working, does not start.

Failed to activate the linter-ui-default package
atom.workspace.getCenter is not a function
Hide Stack Trace
TypeError: atom.workspace.getCenter is not a function
    at new StatusBar (/home/linuxidea/.atom/packages/linter-ui-default/lib/status-bar/index.js:39:43)
    at new LinterUI (/home/linuxidea/.atom/packages/linter-ui-default/lib/main.js:33:22)
    at Object.provideUI (/home/linuxidea/.atom/packages/linter-ui-default/lib/index.js:36:22)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app/src/package.js:398:1)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:225:1)
    at /usr/share/atom/resources/app/src/package.js:194:1
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:100:1)
    at /usr/share/atom/resources/app/src/package.js:187:1
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:184:1)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:557:1)
    at /usr/share/atom/resources/app/src/package-manager.js:359:1
    at /usr/share/atom/resources/app/src/config.js:644:1
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:129:1)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app/src/config.js:835:1)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app/src/config.js:621:1)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app/src/config.js:236:1)
    at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom/resources/app/src/config.js:386:1)
    at Package.module.exports.Package.enable (/usr/share/atom/resources/app/src/package.js:85:1)
    at PackageManager.module.exports.PackageManager.enablePackage (/usr/share/atom/resources/app/src/package-manager.js:180:1)
    at HTMLButtonElement.enablementButtonClickHandler (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:361:1)
The error was thrown from the linter-ui-default package. This issue has already been reported.

**Comment by steelbrain** [comment] 2017-06-27 15:30
Are you sure you are on Atom v1.17.0? Because sources [suggest](https://github.com/atom/atom/blob/v1.17.0/src/workspace.js#L1507) that the method is present in that Atom version

**Comment by JackPot777** [comment] 2017-06-27 17:17
![atom](https://user-images.githubusercontent.com/26742295/27600716-fa7cc740-5b7d-11e7-8e72-2cfcbdc52e31.png)

**Comment by steelbrain** [comment] 2017-06-27 17:55
Can you open the dev console and show us the output of `console.log(atom.workspace.getCenter)`?

**Comment by JackPot777** [comment] 2017-06-27 18:07
/home/linuxidea/.atom/packages/script/node_modules/atom-space-pen-views/lib/text-editor-view.js:40 Uncaught (in promise) TypeError: this.element.getModel is not a function
    at new TextEditorView (/home/linuxidea/.atom/packages/script/node_modules/atom-space-pen-views/lib/text-editor-view.js:40:34)
    at Object.content (/home/linuxidea/.atom/packages/pdf-view/lib/pdf-goto-page-view.js:9:34)
    at Builder.tag (/home/linuxidea/.atom/packages/script/node_modules/space-pen/lib/space-pen.js:281:19)
    at Function.View.(anonymous function) [as div] (/home/linuxidea/.atom/packages/script/node_modules/space-pen/lib/space-pen.js:83:49)
    at Function.content (/home/linuxidea/.atom/packages/pdf-view/lib/pdf-goto-page-view.js:8:17)
    at Function.<anonymous> (/home/linuxidea/.atom/packages/script/node_modules/space-pen/lib/space-pen.js:156:31)
    at Function.View.buildHtml (/home/linuxidea/.atom/packages/script/node_modules/space-pen/lib/space-pen.js:123:10)
    at PdfGoToPageView.View [as constructor] (/home/linuxidea/.atom/packages/script/node_modules/space-pen/lib/space-pen.js:155:33)
    at new PdfGoToPageView (/home/linuxidea/.atom/packages/pdf-view/lib/pdf-goto-page-view.js:6:37)
    at createPdfStatusView (/home/linuxidea/.atom/packages/pdf-view/lib/pdf-editor.js:65:3)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:129:1)
    at /usr/share/atom/resources/app/src/package-manager.js:521:1

**Comment by JackPot777** [comment] 2017-06-27 18:21
In version.txt  v1.3.14

**Comment by JackPot777** [comment] 2017-06-27 18:27
(function (exports, require, module, __filename, __dirname, process, global) { (function() {
  var $, TextEditorView, View, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = require('space-pen'), View = _ref.View, $ = _ref.$;

  module.exports = TextEditorView = (function(_super) {
    __extends(TextEditorView, _super);

    function TextEditorView(params) {
      var attributes, editor, mini, name, placeholderText, value;
      if (params == null) {
        params = {};
      }
      mini = params.mini, placeholderText = params.placeholderText, attributes = params.attributes, editor = params.editor;
      if (attributes == null) {
        attributes = {};
      }
      if (mini != null) {
        attributes['mini'] = mini;
      }
      if (placeholderText != null) {
        attributes['placeholder-text'] = placeholderText;
      }
      if (editor != null) {
        this.element = atom.views.getView(editor);
      } else {
        this.element = document.createElement('atom-text-editor');
      }
      for (name in attributes) {
        value = attributes[name];
        this.element.setAttribute(name, value);
      }
      if (this.element.__spacePenView != null) {
        this.element.__spacePenView = this;
        this.element.__allowViewAccess = true;
      }
      TextEditorView.__super__.constructor.apply(this, arguments);
      this.setModel(this.element.getModel());   **X-this error**
    }

    TextEditorView.prototype.setModel = function(model) {
      this.model = model;
    };

    TextEditorView.prototype.getModel = function() {
      return this.model;
    };

    TextEditorView.prototype.getText = function() {
      return this.model.getText();
    };

    TextEditorView.prototype.setText = function(text) {
      return this.model.setText(text);
    };

    TextEditorView.prototype.hasFocus = function() {
      return this.element.hasFocus();
    };

    return TextEditorView;

  })(View);

}).call(this);

});

**Comment by JackPot777** [comment] 2017-06-27 18:29
/* @flow */
/* eslint-disable import/no-duplicates */

import { Emitter, CompositeDisposable } from 'atom'
import type { TextEditor, Disposable } from 'atom'

import * as Helpers from './helpers'
import * as Validate from './validate'
import { $version, $activated, $requestLatest, $requestLastReceived } from './helpers'
import type { Linter } from './types'

class LinterRegistry {
  emitter: Emitter;
  linters: Set<Linter>;
  lintOnChange: boolean;
  ignoreVCS: boolean;
  ignoreGlob: string;
  lintPreviewTabs: boolean;
  subscriptions: CompositeDisposable;
  disabledProviders: Array<string>;

  constructor() {
    this.emitter = new Emitter()
    this.linters = new Set()
    this.subscriptions = new CompositeDisposable()

    this.subscriptions.add(atom.config.observe('linter.lintOnChange', (lintOnChange) => {
      this.lintOnChange = lintOnChange
    }))
    this.subscriptions.add(atom.config.observe('core.excludeVcsIgnoredPaths', (ignoreVCS) => {
      this.ignoreVCS = ignoreVCS
    }))
    this.subscriptions.add(atom.config.observe('linter.ignoreGlob', (ignoreGlob) => {
      this.ignoreGlob = ignoreGlob
    }))
    this.subscriptions.add(atom.config.observe('linter.lintPreviewTabs', (lintPreviewTabs) => {
      this.lintPreviewTabs = lintPreviewTabs
    }))
    this.subscriptions.add(atom.config.observe('linter.disabledProviders', (disabledProviders) => {
      this.disabledProviders = disabledProviders
    }))
    this.subscriptions.add(this.emitter)
  }
  hasLinter(linter: Linter): boolean {
    return this.linters.has(linter)
  }
  addLinter(linter: Linter, legacy: boolean = false) {
    const version = legacy ? 1 : 2
    if (!Validate.linter(linter, version)) {
      return
    }
    linter[$activated] = true
    if (typeof linter[$requestLatest] === 'undefined') {
      linter[$requestLatest] = 0
    }
    if (typeof linter[$requestLastReceived] === 'undefined') {
      linter[$requestLastReceived] = 0
    }
    linter[$version] = version
    this.linters.add(linter)
  }
  getProviders(): Array<Linter> {
    return Array.from(this.linters)
  }
  deleteLinter(linter: Linter) {
    if (!this.linters.has(linter)) {
      return
    }
    linter[$activated] = false
    this.linters.delete(linter)
  }
  async lint({ onChange, editor } : { onChange: boolean, editor: TextEditor }): Promise<boolean> {
    const filePath = editor.getPath()

    if (
      (onChange && !this.lintOnChange) ||                                                       // Lint-on-change mismatch
      !filePath ||                                                                              // Not saved anywhere yet
      Helpers.isPathIgnored(editor.getPath(), this.ignoreGlob, this.ignoreVCS) ||               // Ignored by VCS or Glob
      (!this.lintPreviewTabs && atom.workspace.getActivePane().getPendingItem() === editor)     // Ignore Preview tabs
    ) {
      return false
    }

    const scopes = Helpers.getEditorCursorScopes(editor)

    const promises = []
    for (const linter of this.linters) {
      if (!Helpers.shouldTriggerLinter(linter, onChange, scopes)) {
        continue
      }
      if (this.disabledProviders.includes(linter.name)) {
        continue
      }
      const number = ++linter[$requestLatest]
      const statusBuffer = linter.scope === 'file' ? editor.getBuffer() : null
      const statusFilePath = linter.scope === 'file' ? filePath : null

      this.emitter.emit('did-begin-linting', { number, linter, filePath: statusFilePath })
      promises.push(new Promise(function(resolve) {
        // $FlowIgnore: Type too complex, duh
        resolve(linter.lint(editor))
      }).then((messages) => {
        this.emitter.emit('did-finish-linting', { number, linter, filePath: statusFilePath })
        if (linter[$requestLastReceived] >= number || !linter[$activated] || (statusBuffer && !statusBuffer.isAlive())) {
          return
        }
        linter[$requestLastReceived] = number
        if (statusBuffer && !statusBuffer.isAlive()) {
          return
        }

        if (messages === null) {
          // NOTE: Do NOT update the messages when providers return null
          return
        }

        let validity = true
        // NOTE: We are calling it when results are not an array to show a nice notification
        if (atom.inDevMode() || !Array.isArray(messages)) {
          validity = linter[$version] === 2 ? Validate.messages(linter.name, messages) : Validate.messagesLegacy(linter.name, messages)
        }
        if (!validity) {
          return
        }

        if (linter[$version] === 2) {
          Helpers.normalizeMessages(linter.name, messages)
        } else {
          Helpers.normalizeMessagesLegacy(linter.name, messages)
        }
        this.emitter.emit('did-update-messages', { messages, linter, buffer: statusBuffer })
      }, (error) => {
        this.emitter.emit('did-finish-linting', { number, linter, filePath: statusFilePath })
        atom.notifications.addError(`[Linter] Error running ${linter.name}`, {
          detail: 'See Console for more info. (Open View -> Developer -> Toggle Developer Tools)',
        })
        console.error(`[Linter] Error running ${linter.name}`, error)
      }))
    }

    await Promise.all(promises)
    return true
  }
  onDidUpdateMessages(callback: Function): Disposable {
    return this.emitter.on('did-update-messages', callback)
  }
  onDidBeginLinting(callback: Function): Disposable {
    return this.emitter.on('did-begin-linting', callback)
  }
  onDidFinishLinting(callback: Function): Disposable {
    return this.emitter.on('did-finish-linting', callback)
  }
  dispose() {
    this.linters.clear()
    this.subscriptions.dispose()
  }
}

module.exports = LinterRegistry

**Comment by steelbrain** [comment] 2017-06-27 18:30
Hi @JackPot777 

Is it possible for you to recompile the Atom package from it's latest sources? That would be immensely helpful

**Comment by JackPot777** [comment] 2017-06-27 18:34
Мне бы не хотелось этого делать. Как мне откатить ваш модуль на предыдущую версию?

**Comment by steelbrain** [comment] 2017-06-27 18:35
Google translate tells me you don't want to compile it from source so here's a temp fix

```
apm install linter-ui-default@1.6.1
```

**Comment by JackPot777** [comment] 2017-06-27 18:37
Ok. Thank's.

**Comment by JackPot777** [comment] 2017-06-27 18:39
Right says. Don't want to. A lot to configure! While not critical.

**Comment by Arcanemagus** [comment] 2017-06-29 21:03
Marking this as closed, you are running a custom build of Atom that seems to disagree with itself as to what version it actually is. If you are able to reproduce this on a stable build please comment back here, thanks!

**Closed by Arcanemagus** 2017-06-29 21:03 UTC
Labels: unconfirmed bug

**Comment by JackPot777** [comment] 2017-06-29 21:18
Atom in the Assembly only on a 64 bit system. For 32 bits you need to compile from source files. Solved your problem, removed getCenter() of the files that gave an error.

**Comment by Arcanemagus** [comment] 2017-06-29 21:47
@JackPot777 `atom.workspace.getCenter` exists in Atom v1.17.0, as pointed out by @steelbrain earlier. Whatever version you are running is reporting v1.17.0 in some places, but it definitely isn't v1.17.0.

**Comment by Arcanemagus** [comment] 2017-06-29 21:51
Looked up the commit from your screenshot, that's 164 commits before v1.17.0-beta0, and 193 commits before v1.17.0. You are running a version of Atom that is too old to support this package and just need to update.

**Comment by JackPot777** [comment] 2017-06-30 09:46
Ok. Give me please an update for the 32 bit system linux.
