### ISSUE TITLE
panel never displays

### ISSUE THREAD

**Issue by focusaurus** [steelbrain/linter-ui-default#518] opened 2018-10-15 23:31 UTC
I can never see the linter-ui-default panel with my details. The linter is working and I have the gutter circles, squigly lines in the editor, and squigly lines in the tree view. I have a widget in the bottom toolbar that shows the error/warning counts, but clicking on it never shows the detail panel. The "Linter UI Default: Toggle Panel" command from the command bar does nothing. Not sure if this issue is the same as #425 or not, but I don't think I have other tabs in my bottom panel, just other widgets.

Atom: 1.31.2
OS: Linux Mint 19
```
apm ls|grep linter
├── linter@2.2.0
├── linter-eslint@8.4.1
├── linter-js-yaml@1.3.0 (disabled)
├── linter-jsonlint@1.3.0
├── linter-markdown@5.2.2
├── linter-rust@0.9.0 (disabled)
├── linter-scss-lint@3.1.1
├── linter-shellcheck@1.5.0
├── linter-swagger@0.5.1 (disabled)
├── linter-terraform-syntax@1.2.4 (disabled)
├── linter-tslint@1.9.1
├── linter-ui-default@1.7.1
├── linter-xmllint@1.4.4 (disabled)
```

Here's a screenshot

![screenshot from 2018-10-15 17-30-06-linter-ui-default](https://user-images.githubusercontent.com/482377/46983943-090d2000-d0a0-11e8-8ce3-4f1b165389d8.png)

**Comment by alexgvozden** [comment] 2019-08-08 05:52
same here, this part of extension is not working any more it seems

**Comment by focusaurus** [comment] 2019-08-10 16:41
FYI I have paid a $50 USD bounty for a fix to this issue:

https://www.bountysource.com/issues/64787205-panel-never-displays

**Comment by willy2dg** [comment] 2019-08-12 18:27
I am taking a look to solve the issue

**Comment by willy2dg** [comment] 2019-08-19 02:40
Hello @focusaurus, after investigating a bit, I just sent a PR that should solve the problem (assuming it is related to the active panel issue, since it was the single way to reproduce the error). Could you try it ?
If this doesn't works for you, the console output could be so helpful to find a fix.

@steelbrain the PR its okay for you ? Tell me if do you need more info about it.

**Comment by steelbrain** [comment] 2019-08-19 02:49
Thanks for the PR @willy2dg, looks good from a first look. I'll review later today, thanks again

**Comment by focusaurus** [comment] 2019-08-20 13:16
@willy2dg I'm trying to test but hitting issues. Not sure I have the correct procedure to test your branch but here's what I did:

- quit atom
- move `~/.atom/packages/linter-ui-default` (the main one) out of the way
- Clone your fork's master branch into `~/.atom/packages`
- run `npm install` in `~/.atom/packages/linter-ui-default`
- start atom

It looks to be trying to load the new code but failing with `/home/plyons/.atom/packages/linter-ui-default/lib/panel/index.js: Unexpected token (91:2)`. It's saying that's a [known issue](https://github.com/steelbrain/linter-ui-default/issues/460) but that's already closed. Any tips?

**Comment by willy2dg** [comment] 2019-08-20 14:16
Hi @focusaurus , sorry for the inconvenience, seems i removed a parentesis while cleaning up some logs.

What i do to install a local package :

1 - Remove current package from Atom settings and quit Atom
2 - Clone repo
3 - Go to repo folder and run `npm install`
4 - Run `apm link` ( i assume will work if you copy the repo on `~/.atom/packages/linter-ui-default` but i dont tested it )

**Comment by focusaurus** [comment] 2019-08-21 14:04
OK I pulled the new commit and I can see the panel! Hopefully it stays working for good.

**Comment by willy2dg** [comment] 2019-08-21 17:51
I'm glad to hear that, can we close the issue then ?

**Comment by focusaurus** [comment] 2019-08-21 23:32
@steelbrain could you please cut a release with the fix?

**Comment by steelbrain** [comment] 2019-08-22 15:04
I'm busy with work, I'll be able to review this weekend, thank you for your patience! :)

**Comment by willy2dg** [comment] 2019-08-25 20:15
@steelbrain sorry for insisting, but I would appreciate so much if you review the PR to close the issue. Thanks! 😳

**Comment by steelbrain** [comment] 2019-08-25 21:22
v1.8.0 is out now with a potential fix, please do try and let us know!

**Closed** 2019-08-25 21:27 UTC
