### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by lepirlouit** [steelbrain/linter-ui-default#478] opened 2018-02-07 09:55 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.10

### Stack Trace

Uncaught Error: Requested measurement of a line component that is not currently rendered

```
At /usr/share/atom/resources/app/src/text-editor-component.js:2289

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (/usr/share/atom/resources/app/src/text-editor-component.js:2278:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/usr/share/atom/resources/app/src/text-editor-component.js:2271:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/usr/share/atom/resources/app/src/text-editor-component.js:400:16)
    at TextEditorComponent.updateSync (/usr/share/atom/resources/app/src/text-editor-component.js:284:18)
    at TextEditorComponent.pixelPositionForScreenPosition (/usr/share/atom/resources/app/src/text-editor-component.js:206:18)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:243:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:178:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -1:18.4.0 core:paste (input.hidden-input)
  3x -1:17.8.0 intentions:highlight (input.hidden-input)
     -1:05.4.0 core:copy (input.hidden-input)
     -0:57.1.0 editor:newline (input.hidden-input)
     -0:56.8.0 intentions:highlight (input.hidden-input)
     -0:56.8.0 core:paste (input.hidden-input)
     -0:55.8.0 core:select-up (input.hidden-input)
  4x -0:55.4.0 core:select-down (input.hidden-input)
     -0:54 core:backspace (input.hidden-input)
  3x -0:53.2.0 core:move-down (input.hidden-input)
 11x -0:52.4.0 core:select-down (input.hidden-input)
     -0:49.9.0 editor:select-to-end-of-word (input.hidden-input)
     -0:48.7.0 core:select-right (input.hidden-input)
  3x -0:45 core:backspace (input.hidden-input)
     -0:05.5.0 core:move-up (input.hidden-input)
     -0:04.9.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 12.1.1 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
file-icons 2.1.16 
git-plus 7.10.0 
intentions 1.1.5 
language-babel 2.83.1 
language-javascript-jsx 0.3.7 
language-jsx 0.1.1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.6.10 
local-history 4.3.1 
platformio-ide-terminal 2.8.0 
```

**Comment by Arcanemagus** [comment] 2018-02-08 18:18
Duplicate of #418

**Comment by Arcanemagus** [comment] 2018-02-08 18:18
This can be tracked on the Atom repo at https://github.com/atom/atom/issues/15263.

**Closed by Arcanemagus** 2018-02-08 18:18 UTC
