### ISSUE TITLE
version 1.6.0 does no longer allow to click on line

### ISSUE THREAD

**Issue by doberkofler** [steelbrain/linter-ui-default#337] opened 2017-05-29 07:35 UTC
It seems as if starting with version 1.6.0 there are some problem when clicking on the line of an error to get to the corresponding line in the editor.
I've noticed when using the Flow IDE that sometimes after having clicked on the line, the panel just closes, other times nothing happens and very few times (mostly after trying a couple of times) the expected behavior is provided.
Atom: 1.17.2
linter: 2.1.4
linter-ui-default: 1.6.0
flow-ide: 1.5.0

**Comment by steelbrain** [comment] 2017-05-29 07:36
Oh Boy, we might have to flip defaults for `hidePanelWhenEmpty` (cc @Arcanemagus)

@doberkofler Can you report your config value of `hidePanelWhenEmpty`?

**Comment by doberkofler** [comment] 2017-05-29 07:50
@steelbrain That's quick ;-) and thank you for your great work!

`hidePanelWhenEmpty` is currently enabled but when disabling it and I click on a line, the panel content gets greyed out and only appears again when closing and reopening it.

**Comment by doberkofler** [comment] 2017-05-29 07:52
Settings:
![image](https://cloud.githubusercontent.com/assets/1009585/26541059/6ef4476a-4454-11e7-8fa5-0f3f8911abc2.png)

**Comment by Conanza** [comment] 2017-06-02 19:38
I believe I'm seeing the same issue as @doberkofler, where the panel will not appear on its own when the cursor is on a line with an issue. If I manually click to open the panel, the panel doesn't hide itself when moving the cursor to a line without any issues.

The changelog mentioned "Only hide/show dock when Linter is the active item". Not sure if this has anything to do with my issue.

**Comment by Arcanemagus** [comment] 2017-06-29 20:45
I'm marking this as closed since the original issue reported by @doberkofler was fixed in v1.6.2.

@Conanza I _can_ reproduce your issue of "Hide Panel when empty" not working when "Panel represents" is set to "Current Line". Can you please file a new issue to track that bug?

**Closed by Arcanemagus** 2017-06-29 20:45 UTC
Labels: question

**Comment by Conanza** [comment] 2017-06-29 20:52
@Arcanemagus sure
