### ISSUE TITLE
Issues with new blood-pressure-friendly tooltips

### ISSUE THREAD

**Issue by pingshunhuangalex** [steelbrain/linter-ui-default#309] opened 2017-05-17 23:32 UTC
Hi @steelbrain 
I like the new tooltip style you put in, but it introduces some new issues.

1. It would be nice if you can make the tooltip not transparent as it goes messy when it overlaps with codes
2. It would be nice to restrain the height of the tooltip, instead of letting it going crazy.

Thanks.

![image](https://cloud.githubusercontent.com/assets/17170199/26180443/dc5f49c2-3bac-11e7-8083-67136adfaa46.png)

**Comment by steelbrain** [comment] 2017-05-17 23:38
Hi @pingshunhuangalex 

Can you share what theme that is? The tooltips work perfectly with the One Dark Light & Dark themes.
<img width="560" alt="screen shot 2017-05-18 at 4 38 16 am" src="https://cloud.githubusercontent.com/assets/4278113/26180590/d591010e-3b83-11e7-89e9-d9651037f4d7.png">

**Comment by pingshunhuangalex** [comment] 2017-05-17 23:40
Sorry @steelbrain I didn't realise it 's a theme related one.
I'm using `material-ui-dark`.
Let me know if this is not related to you. I'll repost it at theme's repository. Thanks.

**Comment by steelbrain** [comment] 2017-05-17 23:45
Can confirm, is a theme issue
<img width="279" alt="screen shot 2017-05-18 at 4 43 45 am" src="https://cloud.githubusercontent.com/assets/4278113/26180727/9b07a2f8-3b84-11e7-9281-0f000cff9f95.png">

Tell the theme authors that Linter is using `@background-color-highlight` as the tooltip background color and that it should not be transparent

**Comment by pingshunhuangalex** [comment] 2017-05-17 23:51
@steelbrain How about the max width then? Is this an intended behavior? Thanks.

**Comment by Arcanemagus** [comment] 2017-05-17 23:53
@pingshunhuangalex `material-ui` (_not_ `material-ui-dark`) follows your syntax theme, and the v2 branch has many improvements.

The large message there is coming from ESLint, it seems recent versions have started including a bunch of context in the main message and special handling to remove it hasn't been added yet.

**Comment by steelbrain** [comment] 2017-05-17 23:53
That is yet another instance of a known bug in linter-eslint where the syntax error would include some context of code (tho irrelevant inside Atom) (cc @Arcanemagus)

**Comment by pingshunhuangalex** [comment] 2017-05-18 00:00
Sorry @Arcanemagus You are right. `material-ui`, and `material syntax dark`. I always get messed up here.

No need to rush with any of the issues here. I'm just reporting everything I can find when I'm using it.

**Comment by Arcanemagus** [comment] 2017-05-18 20:12
So this doesn't get forgotten about:

This issue is reproducible with the Atom Dark (and Light) themes that are included with Atom itself, so this needs to either be worked around here, or the affected themes fixed. Since the "Atom ___" don't look like they are maintained very well, it will probably end up that a workaround here is needed for a while.

**Comment by JGH1000** [comment] 2017-05-19 06:10
It seems that there are different problems depending on the theme - I tried using alternatives (I think nucleus) and the text on the messages is so dark it cannot be read. When working the tooltips will look really nice though.

**Comment by palimondo** [comment] 2017-05-20 15:33
The issue is present with `native-ui` theme, too.

**Comment by steelbrain** [comment] 2017-05-20 15:36
Fix is up in https://github.com/steelbrain/linter-ui-default/pull/321

**Comment by steelbrain** [comment] 2017-05-21 20:34
Fixed by #321. For reference, here's what the latest styles would look like


Apex
<img width="306" alt="screen shot 2017-05-22 at 1 27 55 am" src="https://cloud.githubusercontent.com/assets/4278113/26287119/eb3217ca-3e8d-11e7-8dd6-1d848a961750.png">

Atom Dark
<img width="284" alt="screen shot 2017-05-22 at 1 28 19 am" src="https://cloud.githubusercontent.com/assets/4278113/26287120/f4e6176c-3e8d-11e7-8ea8-eade52d888bb.png">

Atom Light
<img width="292" alt="screen shot 2017-05-22 at 1 28 38 am" src="https://cloud.githubusercontent.com/assets/4278113/26287121/0137919e-3e8e-11e7-91f2-693603adc209.png">

Atom Material
<img width="306" alt="screen shot 2017-05-22 at 1 28 55 am" src="https://cloud.githubusercontent.com/assets/4278113/26287123/0b8b3916-3e8e-11e7-9e33-bb392eaacade.png">

Material UI
<img width="323" alt="screen shot 2017-05-22 at 1 29 13 am" src="https://cloud.githubusercontent.com/assets/4278113/26287125/160ce7b8-3e8e-11e7-81eb-9e8b2d05ed76.png">

Nord Atom
<img width="296" alt="screen shot 2017-05-22 at 1 29 29 am" src="https://cloud.githubusercontent.com/assets/4278113/26287128/1e341eac-3e8e-11e7-8a29-68313e40dbb4.png">

One Dark
<img width="313" alt="screen shot 2017-05-22 at 1 29 42 am" src="https://cloud.githubusercontent.com/assets/4278113/26287130/2677afb6-3e8e-11e7-8d97-e0b30696e35b.png">

One Light
<img width="280" alt="screen shot 2017-05-22 at 1 29 56 am" src="https://cloud.githubusercontent.com/assets/4278113/26287132/2eb72332-3e8e-11e7-8880-179c813157e3.png">

**Closed by steelbrain** 2017-05-21 20:34 UTC
Labels: external, ui
