### ISSUE TITLE
Misaligned icons in status bar

### ISSUE THREAD

**Issue by nwaywood** [steelbrain/linter-ui-default#437] opened 2017-09-15 06:52 UTC
Since the last update, the icons are numbers are not aligned

![image](https://user-images.githubusercontent.com/3773641/30469967-31ed825e-9a36-11e7-8834-e1615a5a02cf.png)

**Comment by Arcanemagus** [comment] 2017-09-15 07:04
Did you restart Atom after the update? Nothing in [the changes](https://github.com/steelbrain/linter-ui-default/compare/v1.6.8...v1.6.9) could have affected that 😕.

**Comment by giannisp** [comment] 2017-09-15 08:48
I confirm the issue since updating to Atom `1.20.0`.
It was happening on linter-ui-default `1.6.8` as well.
<img width="138" alt="screen shot 2017-09-15 at 11 43 48" src="https://user-images.githubusercontent.com/1112194/30474107-36d1e8bc-9a0b-11e7-8811-ad02efdc26fa.png">

**Comment by Arcanemagus** [comment] 2017-09-15 16:08
What theme are you using? I don't see that on `atom-material-ui`:
![image](https://user-images.githubusercontent.com/427137/30492465-66d5dd4a-99f5-11e7-931e-335ee7e48080.png)

**Comment by giannisp** [comment] 2017-09-15 16:18
`One Dark` for both UI/Syntax.

**Comment by Arcanemagus** [comment] 2017-09-15 16:40
Looks like this was caused by https://github.com/atom/one-light-ui/pull/105, trying to figure out if it's something that should be fixed here or there.

**Comment by Arcanemagus** [comment] 2017-09-15 17:45
I've got a potential fix in place, but I'd like feedback as I'm not a UI guy _at all_.

UI | Syntax | Result
-- | ------ | ------
One Dark | One Dark | ![image](https://user-images.githubusercontent.com/427137/30495945-d2bd6430-9a02-11e7-99b2-db86769646f8.png)
One Light | One Light | ![image](https://user-images.githubusercontent.com/427137/30495930-c3bbc76a-9a02-11e7-9d62-4290635a00a8.png)
Atom Material | One Dark | ![image](https://user-images.githubusercontent.com/427137/30495860-8115aaf2-9a02-11e7-9528-dcaf53f391a4.png)
Atom Material | One Light | ![image](https://user-images.githubusercontent.com/427137/30495892-a7f0a758-9a02-11e7-8f14-65f1134ebc53.png)

The icons are much bigger... but they match what virtually every other status bar "widget" is doing now.

**Comment by Arcanemagus** [comment] 2017-09-15 17:52
Ha, @ipaintcode apparently has an alternative fix over in #438. I'm fine with either solution personally.

**Comment by Arcanemagus** [comment] 2017-09-15 18:05
Slight tweak to closer match the current style, I think I almost prefer the larger icons of the first version myself.

UI | Syntax | Result
-- | ------ | ------
One Dark | One Dark | ![image](https://user-images.githubusercontent.com/427137/30496763-4a4abf46-9a05-11e7-9f00-e7dfb70dc8e2.png)
One Light | One Light | ![image](https://user-images.githubusercontent.com/427137/30496805-6e931970-9a05-11e7-84eb-5411c8509a1a.png)
Atom Material | One Dark | ![image](https://user-images.githubusercontent.com/427137/30496887-ab4c72e4-9a05-11e7-8bd0-a0e3a9149736.png)
Atom Material | One Light | ![image](https://user-images.githubusercontent.com/427137/30496848-8f2171a0-9a05-11e7-89eb-d4adb37c7dc7.png)

**Closed** 2017-09-15 18:15 UTC

**Comment by Arcanemagus** [comment] 2017-09-15 18:19
Fixed in v1.6.10, thanks for the report!
