### ISSUE TITLE
Opening a new folder causes cursor-line to appear on every line

### ISSUE THREAD

**Issue by 50Wliu** [steelbrain/linter-ui-default#223] opened 2017-03-20 21:52 UTC
![cursor-line-every-line](https://cloud.githubusercontent.com/assets/2766036/24123378/a1ef6550-0d95-11e7-9bb9-b412fd94caf8.png)

Once the cursor moves off the first line then everything is ok.  I can only reproduce this some of the time.

linter-ui-default@1.2.1

**Comment by steelbrain** [comment] 2017-03-20 21:54
Whoops, will investigate

**Comment by steelbrain** [comment] 2017-04-09 22:59
Unable to reproduce this on master, can you please confirm that this has been fixed by recent changes? (tho none of them were directly intended towards fixing this)

**Comment by 50Wliu** [comment] 2017-04-11 22:14
By "master" do you mean the latest linter-ui-default version, linter-ui-default at HEAD, or atom master?

**Comment by steelbrain** [comment] 2017-04-11 22:24
I meant the linter-ui-default master on Atom v1.16.0-beta0 on macOS

**Comment by 50Wliu** [comment] 2017-04-11 22:27
I do not have macOS, so I will be unable to satisfy that requirement.  I can test under linter-ui-default using Atom v1.16.0-beta0 on Windows 10 x64 later.

**Comment by steelbrain** [comment] 2017-05-17 03:18
Still unable to repro on latest Atom stable/beta

**Closed** 2017-05-17 04:41 UTC
Labels: confirmed bug, ui
